/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reports_Package;

import System_Package.Writer;
import Database_Package.DBConnectivity;
import java.sql.Date;
import java.sql.ResultSet;
import java.util.ArrayList;

/**
 * Shows how to construct an Individual Report object and its associated variables and methods.
 * 
 * @author      Felice Gregorio
 * @version     (11/04/2018) version 2.3
 * @since       (26/03/2018) version 1
 */
public class IndividualReport extends Report {
    /** The connectivity to the database.  */
    private final DBConnectivity myDB = new DBConnectivity();
    /** The customer ID for which the report should be generated for. */
    private String custID;
    
    /**
    * Constructor for a new Individual Report object.
    * <p>
    * This is the constructor used when creating and generating a new Individual Report.
    * It is needed to create an instance of this class.
    * 
    * @param custID The customer ID of the customer to generate the report for.
    * @param start The starting date range of the report.
    * @param end The ending date range of the report.
    * 
    */
    public IndividualReport(String custID, Date start, Date end) {
        super.initialise("Individual Report", start, end);
        this.custID = custID;
    }

    /**
    * Generate Individual Report.
    * <p>
    * This is a concrete method which runs the SQL query use to generate an Individual Report 
    * and returns an ArrayList of ResultSets which stores the ResultSet generated by the query. 
    * 
    * @return Returns an ArrayList of ResultSets containing ResultSets relevant to the report.
    */
    @Override
    public ArrayList<ResultSet> generate(boolean write) {
        ArrayList<ResultSet> rss = new ArrayList<>();
        myDB.connect();
        rss.add(myDB.execStoredProc("{ call spIndividualReport(?, ?, ?) }", custID, getStart(), getEnd()));
        
        if (write){
            Writer rw = new Writer("generatedReports.txt");
            rw.writeGeneratedReport("Individual Report", getStart(), getEnd(), custID);
        }
        
        return rss;
    }

    /**
    * Get Customer ID.
    * <p>
    * This function retrieves the customer ID relevant for the report.
    * 
    * @return Returns the Customer ID.
    * 
    */
    public String getCustID() {
        return custID;
    }

    /**
    * Set Customer ID.
    * <p>
    * This function sets/changes the customer ID relevant for the report.
    * 
    * @param custID The customer ID to be set.
    * 
    */
    public void setCustID(String custID) {
        this.custID = custID;
    }
    
    /**
    * Get Database Connectivity.
    * <p>
    * This function retrieves the database connectivity object used to generate this report.
    * 
    * @return Returns the database connectivity object.
    * 
    */
    public DBConnectivity getMyDB() {
        return myDB;
    }
}
