/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Package;

import Account_Package.Customer;
import javax.swing.JOptionPane;

/**
 *
 * @author umahm
 */
public class AssignDiscountPlan extends javax.swing.JFrame {
    /** The Employee job role. */
    private final String jobRole;
    /** The Customer that the discount is applied to. */
    private final Customer cust;
    /** The Employees ID. */
    private final String empID;
    
    

    /**
     * Creates new form AssignDiscountPlan
     * @param jobRole The Employee's job role.
     * @param cust  Customer the discount is being applied to.
     * @param empID
     */
    public AssignDiscountPlan(String jobRole, Customer cust, String empID) {
        this.empID = empID;
        this.jobRole = jobRole;
        this.cust = cust;
        initComponents();
        CustomerID_Label.setText("Customer ID: " + cust.getCustID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back_Button = new javax.swing.JButton();
        VariableDiscount_Button = new javax.swing.JButton();
        FixedDiscount_Button = new javax.swing.JButton();
        FlexibleDiscount_Button = new javax.swing.JButton();
        CustomerID_Label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AssignDiscount_Field = new javax.swing.JTextField();
        Logout_Button = new javax.swing.JButton();
        HomePage_Button = new javax.swing.JButton();
        LOGO_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Back_Button.setBackground(new java.awt.Color(0, 153, 255));
        Back_Button.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Back_Button.setForeground(new java.awt.Color(255, 255, 255));
        Back_Button.setText("Back");
        Back_Button.setBorder(null);
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        VariableDiscount_Button.setBackground(new java.awt.Color(0, 153, 255));
        VariableDiscount_Button.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        VariableDiscount_Button.setForeground(new java.awt.Color(255, 255, 255));
        VariableDiscount_Button.setText("Variable");
        VariableDiscount_Button.setBorder(null);
        VariableDiscount_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariableDiscount_ButtonActionPerformed(evt);
            }
        });

        FixedDiscount_Button.setBackground(new java.awt.Color(0, 153, 255));
        FixedDiscount_Button.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        FixedDiscount_Button.setForeground(new java.awt.Color(255, 255, 255));
        FixedDiscount_Button.setText("Fixed");
        FixedDiscount_Button.setBorder(null);
        FixedDiscount_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FixedDiscount_ButtonActionPerformed(evt);
            }
        });

        FlexibleDiscount_Button.setBackground(new java.awt.Color(0, 153, 255));
        FlexibleDiscount_Button.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        FlexibleDiscount_Button.setForeground(new java.awt.Color(255, 255, 255));
        FlexibleDiscount_Button.setText("Flexible");
        FlexibleDiscount_Button.setBorder(null);
        FlexibleDiscount_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlexibleDiscount_ButtonActionPerformed(evt);
            }
        });

        CustomerID_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CustomerID_Label.setText("Customer ID:");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        AssignDiscount_Field.setBackground(new java.awt.Color(0, 153, 255));
        AssignDiscount_Field.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        AssignDiscount_Field.setForeground(new java.awt.Color(255, 255, 255));
        AssignDiscount_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AssignDiscount_Field.setText("Assign Discount Plan");
        AssignDiscount_Field.setBorder(null);

        Logout_Button.setBackground(new java.awt.Color(255, 255, 255));
        Logout_Button.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Logout_Button.setForeground(new java.awt.Color(0, 153, 255));
        Logout_Button.setText("Logout");
        Logout_Button.setBorder(null);
        Logout_Button.setBorderPainted(false);
        Logout_Button.setOpaque(false);
        Logout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_ButtonActionPerformed(evt);
            }
        });

        HomePage_Button.setBackground(new java.awt.Color(255, 255, 255));
        HomePage_Button.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        HomePage_Button.setForeground(new java.awt.Color(0, 153, 255));
        HomePage_Button.setText("Home Page");
        HomePage_Button.setBorder(null);
        HomePage_Button.setBorderPainted(false);
        HomePage_Button.setOpaque(false);
        HomePage_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePage_ButtonActionPerformed(evt);
            }
        });

        LOGO_Label.setText("LOGO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LOGO_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(AssignDiscount_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Logout_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomePage_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Logout_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HomePage_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LOGO_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssignDiscount_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(CustomerID_Label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FixedDiscount_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(VariableDiscount_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addComponent(FlexibleDiscount_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(CustomerID_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VariableDiscount_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FixedDiscount_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlexibleDiscount_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Logout Button
     * <p>
     * Closes the form and takes you back to the login form.
     */
    private void Logout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_ButtonActionPerformed
       
        this.dispose();
        Login_Form l = new Login_Form();
        l.setVisible(true);
    }//GEN-LAST:event_Logout_ButtonActionPerformed
    /**
     * HomePage Button
     * <p>
     * Closes the form and takes you back to the home page form.
     */
    private void HomePage_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePage_ButtonActionPerformed
        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_HomePage_ButtonActionPerformed
    /**
     * Fixed Discount Button
     * <p>
     * Closes the form and takes you to the Fixed discount form.
     */
    private void FixedDiscount_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FixedDiscount_ButtonActionPerformed
        this.dispose();
        if("Office Manager".equals(jobRole)){
        FixedDiscountForm fd = new FixedDiscountForm(jobRole, cust, empID);
        fd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "You do not have access to this feature!", "Access Denied", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_FixedDiscount_ButtonActionPerformed
     /**
     * Variable Discount Button
     * <p>
     * Closes the form and takes you to the Variable discount form.
     */
    private void VariableDiscount_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariableDiscount_ButtonActionPerformed
        this.dispose();
        if("Office Manager".equals(jobRole)){
        VariableDiscountForm vd = new VariableDiscountForm(jobRole, cust, empID);
        vd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "You do not have access to this feature!", "Access Denied", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_VariableDiscount_ButtonActionPerformed
     /**
     * Flexible Discount Button
     * <p>
     * Closes the form and takes you to the Flexible discount form.
     */
    private void FlexibleDiscount_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlexibleDiscount_ButtonActionPerformed
        this.dispose();
        if("Office Manager".equals(jobRole)){
        FlexibleDiscountForm fd = new FlexibleDiscountForm(jobRole, cust, empID);
        fd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "You do not have access to this feature!", "Access Denied", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_FlexibleDiscount_ButtonActionPerformed
     /**
     * Back Button
     * <p>
     * Closes the form taking you back to the previous form.
     */
    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        
        this.dispose();
        SearchCustomer sc = new SearchCustomer(jobRole, empID);
        sc.setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignDiscountPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignDiscountPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignDiscountPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignDiscountPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignDiscountPlan("Office Manager", new Customer("ACC0001"), "FG12").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AssignDiscount_Field;
    private javax.swing.JButton Back_Button;
    private javax.swing.JLabel CustomerID_Label;
    private javax.swing.JButton FixedDiscount_Button;
    private javax.swing.JButton FlexibleDiscount_Button;
    private javax.swing.JButton HomePage_Button;
    private javax.swing.JLabel LOGO_Label;
    private javax.swing.JButton Logout_Button;
    private javax.swing.JButton VariableDiscount_Button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
