/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Package;

import Database_Package.DBConnectivity;
import System_Package.Writer;
import java.io.File;
import java.io.FilenameFilter;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author umahm, Felice Gregorio
 */
public class BackupAndRestore extends javax.swing.JFrame {
    /** The Employee job role. */
    private final String jobRole;
    /** The Employees ID. */
    private final String empID;
     /** The connection to the Database. */
    private final DBConnectivity myDB = new DBConnectivity();
    /** The Backup File. */
    private final File file = new File("/Users/FMG97/BAPERS_Backup/");

    /**
     * Creates new form BackupAndRestore.
     *
     * @param jobRole Employees job role
     * @param empID
     * 
     * @version (11/04/2018) version 2
     * @since (26/03/2018) version 1
     */
    public BackupAndRestore(String jobRole, String empID) {
        this.empID = empID;
        this.jobRole = jobRole;
        initComponents();
        sortList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Restore_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();
        schedule_cmbo = new javax.swing.JComboBox<>();
        schedule_lbl = new javax.swing.JLabel();
        Backup_btn = new javax.swing.JButton();
        RestoreFrom_scrl = new javax.swing.JScrollPane();
        bkup_lst = new javax.swing.JList<>();
        Restore_From_lbl = new javax.swing.JLabel();
        Restore_lbl = new javax.swing.JLabel();
        JobCode_lbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LogOut_btn = new javax.swing.JButton();
        HomePage_btn = new javax.swing.JButton();
        BackupAndRestore_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Restore_btn.setBackground(new java.awt.Color(0, 153, 255));
        Restore_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Restore_btn.setForeground(new java.awt.Color(255, 255, 255));
        Restore_btn.setText("Restore");
        Restore_btn.setBorder(null);
        Restore_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restore_btnActionPerformed(evt);
            }
        });

        Back_btn.setBackground(new java.awt.Color(0, 153, 255));
        Back_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Back_btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn.setText("Back");
        Back_btn.setBorder(null);
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        submit_btn.setBackground(new java.awt.Color(0, 153, 255));
        submit_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("Submit");
        submit_btn.setBorder(null);
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        schedule_cmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily", "Weekly", "Monthly" }));

        schedule_lbl.setText("Backup Schedule:");

        Backup_btn.setBackground(new java.awt.Color(0, 153, 255));
        Backup_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Backup_btn.setForeground(new java.awt.Color(255, 255, 255));
        Backup_btn.setText("Back-up");
        Backup_btn.setBorder(null);
        Backup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Backup_btnActionPerformed(evt);
            }
        });

        RestoreFrom_scrl.setToolTipText("");
        RestoreFrom_scrl.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        bkup_lst.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        DefaultListModel lstModel = new DefaultListModel();

        FilenameFilter ff = (File dir, String name1) -> name1.startsWith("BAPERS_bkup");

        if (!file.exists()){
            JOptionPane.showMessageDialog(null, "Backup folder not found!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            File[] fileList = file.listFiles(ff);
            for(File f : fileList) {
                lstModel.addElement(f.getName());
            }
        }
        bkup_lst.setModel(lstModel);
        RestoreFrom_scrl.setViewportView(bkup_lst);

        Restore_From_lbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Restore_From_lbl.setText("Select backup file:");

        Restore_lbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Restore_lbl.setText("Restore System:");

        JobCode_lbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JobCode_lbl.setText("Back-Up System: ");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        LogOut_btn.setBackground(new java.awt.Color(255, 255, 255));
        LogOut_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        LogOut_btn.setForeground(new java.awt.Color(0, 153, 255));
        LogOut_btn.setText("Logout");
        LogOut_btn.setBorder(null);
        LogOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_btnActionPerformed(evt);
            }
        });

        HomePage_btn.setBackground(new java.awt.Color(255, 255, 255));
        HomePage_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        HomePage_btn.setForeground(new java.awt.Color(0, 153, 255));
        HomePage_btn.setText("Home Page");
        HomePage_btn.setBorder(null);
        HomePage_btn.setMaximumSize(new java.awt.Dimension(65, 19));
        HomePage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePage_btnActionPerformed(evt);
            }
        });

        BackupAndRestore_lbl.setBackground(new java.awt.Color(0, 153, 255));
        BackupAndRestore_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        BackupAndRestore_lbl.setForeground(new java.awt.Color(255, 255, 255));
        BackupAndRestore_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BackupAndRestore_lbl.setText("Backup and Restore");
        BackupAndRestore_lbl.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackupAndRestore_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogOut_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomePage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomePage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BackupAndRestore_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Restore_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(schedule_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(schedule_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Backup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JobCode_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Restore_From_lbl)
                            .addComponent(Restore_lbl)
                            .addComponent(RestoreFrom_scrl, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JobCode_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Restore_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Restore_From_lbl)
                        .addGap(8, 8, 8)
                        .addComponent(Backup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RestoreFrom_scrl, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schedule_lbl)
                    .addComponent(schedule_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit_btn))
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Restore_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * HomePage Button
     * <p>
     * Closes the form and takes you back to the home page form.
     */
    private void HomePage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePage_btnActionPerformed
        if (jobRole.equals("Admin")) {
            JOptionPane.showMessageDialog(null, "As Administrator, you only have access to the Restore funtionality!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            this.dispose();
            HomePage hp = new HomePage(jobRole, empID);
            hp.setVisible(true);
        }
    }//GEN-LAST:event_HomePage_btnActionPerformed
    /**
     * Logout Button
     * <p>
     * Closes the form and takes you back to the login form.
     */
    private void LogOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_btnActionPerformed
        this.dispose();
        Login_Form l = new Login_Form();
        l.setVisible(true);
    }//GEN-LAST:event_LogOut_btnActionPerformed
    /**
     * Backup Button
     * <p>
     * Backs up the database.
     */
    private void Backup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Backup_btnActionPerformed
        if (jobRole.equals("Admin")) {
            JOptionPane.showMessageDialog(null, "As Administrator, you only have access to the Restore funtionality!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            myDB.backup(false);
        }
    }//GEN-LAST:event_Backup_btnActionPerformed
    /**
     * Restore Button
     * <p>
     * Restores from the database.
     */
    private void Restore_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restore_btnActionPerformed
        if (bkup_lst.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Please select a backup file to restore from!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            myDB.restore(file.getPath() + "/" + bkup_lst.getSelectedValue());
        }
    }//GEN-LAST:event_Restore_btnActionPerformed
    /**
     * Back Button
     * <p>
     * Closes the form taking you back to the previous form.
     */
    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        if (jobRole.equals("Admin")) {
            this.dispose();
            Login_Form l = new Login_Form();
            l.setVisible(true);
        } else {
            this.dispose();
            HomePage hp = new HomePage(jobRole, empID);
            hp.setVisible(true);
        }
    }//GEN-LAST:event_Back_btnActionPerformed
     /**
     * Submit Button
     * <p>
     * creates a new backup file.
     */
    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        if (jobRole.equals("Admin")){
            JOptionPane.showMessageDialog(null, "As Administrator, you only have access to the Restore funtionality!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            Writer writer = new Writer("backupSchedule.txt");
            writer.writeBackupSchedule(schedule_cmbo.getSelectedItem().toString());
            JOptionPane.showMessageDialog(null, "Backup Schedule Updated!", "Success!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_submit_btnActionPerformed
    
    /**Sort
    *<p>
    *Sorts through the list.
    */
    public void sortList() {
        ListModel list = bkup_lst.getModel();

        int size = list.getSize();

        String[] data = new String[size];
        for (int i = 0; i < size; i++) {
            data[i] = (String) list.getElementAt(i);
        }

        Arrays.sort(data);

        bkup_lst.setListData(data);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BackupAndRestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BackupAndRestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BackupAndRestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BackupAndRestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BackupAndRestore("Office Manager", "FFG12").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JLabel BackupAndRestore_lbl;
    private javax.swing.JButton Backup_btn;
    private javax.swing.JButton HomePage_btn;
    private javax.swing.JLabel JobCode_lbl;
    private javax.swing.JButton LogOut_btn;
    private javax.swing.JScrollPane RestoreFrom_scrl;
    private javax.swing.JLabel Restore_From_lbl;
    private javax.swing.JButton Restore_btn;
    private javax.swing.JLabel Restore_lbl;
    private javax.swing.JList<String> bkup_lst;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> schedule_cmbo;
    private javax.swing.JLabel schedule_lbl;
    private javax.swing.JButton submit_btn;
    // End of variables declaration//GEN-END:variables
}
