/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Package;

import Account_Package.Customer;
import Database_Package.DBConnectivity;
import Process_Package.CardPay;
import Process_Package.Job;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author umahm, Kimberly Eslami
 * @version (11/04/18) version 3
 * @since (03/04/2018) version 1
 */
public class CardPayment extends javax.swing.JFrame {
    /** The Employees ID. */
    private final String empID;
    /** The Employee job role. */
    private final String jobRole;
    /** The Customer that is making the payment. */
    private final Customer cust;
    /** The job that is being paid for. */
    private final Job job;
    /** The VAT to be calculated. */
    private final double VAT = 0.2;
    /** Decimal format for the totals. */
    private DecimalFormat df = new DecimalFormat(".##");
    /** The cost of the job not including VAT. */
    private double subTot;
    /** The total cost of the job including VAT and a discount. */
    private double totCost;

    /**
     * Creates new form CardPayment
     *
     * @param jobRole employees job role
     * @param cust customer paying
     * @param job job being paid for
     * @param empID
     */
    public CardPayment(String jobRole, Customer cust, Job job, String empID) {
        this.empID = empID;
        this.jobRole = jobRole;
        this.cust = cust;
        this.job = job;
        initComponents();
        
        DBConnectivity myDB = new DBConnectivity();
        myDB.connect();
        Connection con = myDB.getConn();
        try {
            con.setAutoCommit(false);
            
            ResultSet rs = myDB.read("SELECT `sub-total`, totalCost FROM Invoice WHERE invoice_ID = '" + job.getInvoiceID() + "'");
            while (rs.next()) {
                subTot = rs.getDouble("sub-total");
                totCost = rs.getDouble("totalCost");
                subTot_lbl.setText("Sub-Total: £" + df.format(subTot));
                totCost_lbl.setText("Total Cost (Inc. VAT): £" + df.format(totCost));
            }
            con.commit();
        } catch (SQLException ex) {
            if (con != null) {
                try {
                    System.err.print("Transaction rolling back!");
                    con.rollback();
                } catch (SQLException ex1) {
                    Logger.getLogger(DBConnectivity.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }
        }finally{
            try {
                con.setAutoCommit(true); 
            } catch (SQLException ex) {
                Logger.getLogger(CardPayment.class.getName()).log(Level.SEVERE, null, ex);
            }
            myDB.closeConnection();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Submit_btn = new javax.swing.JButton();
        Cancel_btn = new javax.swing.JButton();
        Amount_txt = new javax.swing.JTextField();
        Amount_lbl = new javax.swing.JLabel();
        subTot_lbl = new javax.swing.JLabel();
        totCost_lbl = new javax.swing.JLabel();
        ExpiryDate = new com.toedter.calendar.JDateChooser();
        Date_btn = new javax.swing.JButton();
        ExpiryDate_lbl = new javax.swing.JLabel();
        Type_lbl = new javax.swing.JLabel();
        Type_cmbo = new javax.swing.JComboBox<>();
        cardNum_lbl = new javax.swing.JLabel();
        cardNum_txt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        CardPayment_lbl = new javax.swing.JLabel();
        LogOut_btn = new javax.swing.JButton();
        HomePage_btn = new javax.swing.JButton();
        Date_lbl = new javax.swing.JLabel();
        cvc_lbl = new javax.swing.JLabel();
        cvc_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Submit_btn.setBackground(new java.awt.Color(0, 153, 255));
        Submit_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        Submit_btn.setText("Submit");
        Submit_btn.setBorder(null);
        Submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_btnActionPerformed(evt);
            }
        });

        Cancel_btn.setBackground(new java.awt.Color(0, 153, 255));
        Cancel_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        Cancel_btn.setText("Cancel");
        Cancel_btn.setBorder(null);
        Cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_btnActionPerformed(evt);
            }
        });

        Amount_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Amount_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Amount_txtActionPerformed(evt);
            }
        });
        Amount_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Amount_txtKeyTyped(evt);
            }
        });

        Amount_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Amount_lbl.setText("Amount:");

        subTot_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        subTot_lbl.setText("Sub-Total:");

        totCost_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        totCost_lbl.setText("Total Cost (Inc. VAT):");

        ExpiryDate.setDateFormatString("MMM-yyyy");

        Date_btn.setBackground(new java.awt.Color(0, 153, 255));
        Date_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Date_btn.setForeground(new java.awt.Color(255, 255, 255));
        Date_btn.setText("Get Date");
        Date_btn.setBorder(null);
        Date_btn.setBorderPainted(false);
        Date_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_btnActionPerformed(evt);
            }
        });

        ExpiryDate_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        ExpiryDate_lbl.setText("Expiry Date:");

        Type_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Type_lbl.setText("Type:");

        Type_cmbo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Type_cmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Visa", "American Express", "MasterCard" }));

        cardNum_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        cardNum_lbl.setText("Card Number:");

        cardNum_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cardNum_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNum_txtActionPerformed(evt);
            }
        });
        cardNum_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNum_txtKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        CardPayment_lbl.setBackground(new java.awt.Color(0, 153, 255));
        CardPayment_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        CardPayment_lbl.setForeground(new java.awt.Color(255, 255, 255));
        CardPayment_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CardPayment_lbl.setText("Card Payment");
        CardPayment_lbl.setOpaque(true);

        LogOut_btn.setBackground(new java.awt.Color(255, 255, 255));
        LogOut_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        LogOut_btn.setForeground(new java.awt.Color(0, 153, 255));
        LogOut_btn.setText("Logout");
        LogOut_btn.setBorder(null);
        LogOut_btn.setContentAreaFilled(false);
        LogOut_btn.setOpaque(true);
        LogOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_btnActionPerformed(evt);
            }
        });

        HomePage_btn.setBackground(new java.awt.Color(255, 255, 255));
        HomePage_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        HomePage_btn.setForeground(new java.awt.Color(0, 153, 255));
        HomePage_btn.setText("Home Page");
        HomePage_btn.setBorder(null);
        HomePage_btn.setContentAreaFilled(false);
        HomePage_btn.setMaximumSize(new java.awt.Dimension(65, 19));
        HomePage_btn.setOpaque(true);
        HomePage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePage_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CardPayment_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(LogOut_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomePage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HomePage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LogOut_btn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(CardPayment_lbl)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Date_lbl.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        cvc_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        cvc_lbl.setText("CVC Code:");

        cvc_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        cvc_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvc_txtActionPerformed(evt);
            }
        });
        cvc_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cvc_txtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addComponent(Cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(cardNum_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cardNum_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(391, 391, 391))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subTot_lbl)
                            .addComponent(totCost_lbl)
                            .addComponent(Amount_lbl)
                            .addComponent(ExpiryDate_lbl)
                            .addComponent(Type_lbl)
                            .addComponent(cvc_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Type_cmbo, javax.swing.GroupLayout.Alignment.LEADING, 0, 198, Short.MAX_VALUE)
                            .addComponent(ExpiryDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Amount_txt)
                            .addComponent(cvc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Date_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Date_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNum_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNum_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvc_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Type_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExpiryDate_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amount_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subTot_lbl)
                .addGap(18, 18, 18)
                .addComponent(totCost_lbl)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  /**
     * Submit button
     * <p>
     * Submits the Card Payment and stores it into the database.
     */
    private void Submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_btnActionPerformed

        String typeOfPayment;
        typeOfPayment = "Card";

        String amount = Amount_txt.getText();
        float totalAmount = Float.parseFloat(amount);

        String cardNum = cardNum_txt.getText();
        
        String cvc_String = cvc_txt.getText();
        int cvc = Integer.parseInt(cvc_String);

        if (amount.isEmpty() && cvc_String.isEmpty() && Type_cmbo.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter All Fields ");
        } else {
            try {
                String date = Date_lbl.getText();
                CardPay cp = new CardPay(job.getJobID(), typeOfPayment, totalAmount, cardNum, cvc, Type_cmbo.getSelectedItem().toString(), date);
                JOptionPane.showMessageDialog(null, "Payment Complete ");
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(CardPayment.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_Submit_btnActionPerformed

    private void cardNum_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNum_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNum_txtActionPerformed
    /**
     * Logout Button
     * <p>
     * Closes the form and takes you back to the login form.
     */
    private void LogOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_btnActionPerformed

        this.dispose();
        Login_Form l = new Login_Form();
        l.setVisible(true);
    }//GEN-LAST:event_LogOut_btnActionPerformed
    /**
     * HomePage Button
     * <p>
     * Closes the form and takes you back to the home page form.
     */
    private void HomePage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePage_btnActionPerformed

        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_HomePage_btnActionPerformed
    /**
     * Card Digits text field restriction
     * <p>
     * Restricts the field to only allows 4 numbers to be entered.
     */
    private void cardNum_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNum_txtKeyTyped

        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_cardNum_txtKeyTyped
    /**
     * Cancel Button
     * <p>
     * Closes the form taking you back to the previous form.
     */
    private void Cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_btnActionPerformed

        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_Cancel_btnActionPerformed

    private void Amount_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Amount_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Amount_txtActionPerformed
    /**
     * Amount text field restriction
     * <p>
     * Restricts the field to only allows numbers and '.' to be entered.
     */
    private void Amount_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Amount_txtKeyTyped

        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || vChar == '.'
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }

    }//GEN-LAST:event_Amount_txtKeyTyped
    /** Get Date button
     * <p>
     * Gets the date from the calendar and returns the date in the label.
     */
    private void Date_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_btnActionPerformed

        SimpleDateFormat dcn = new SimpleDateFormat("MM/yy");
        String date = dcn.format(ExpiryDate.getDate());
        Date_lbl.setText(date);

    }//GEN-LAST:event_Date_btnActionPerformed

    private void cvc_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvc_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvc_txtActionPerformed

    private void cvc_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvc_txtKeyTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }

        if (cvc_txt.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_cvc_txtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CardPayment("Office Manager", new Customer("ACC0001"), new Job("ABN54"), "FG12").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CardPayment.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount_lbl;
    private javax.swing.JTextField Amount_txt;
    private javax.swing.JButton Cancel_btn;
    private javax.swing.JLabel CardPayment_lbl;
    private javax.swing.JButton Date_btn;
    private javax.swing.JLabel Date_lbl;
    private com.toedter.calendar.JDateChooser ExpiryDate;
    private javax.swing.JLabel ExpiryDate_lbl;
    private javax.swing.JButton HomePage_btn;
    private javax.swing.JButton LogOut_btn;
    private javax.swing.JButton Submit_btn;
    private javax.swing.JComboBox<String> Type_cmbo;
    private javax.swing.JLabel Type_lbl;
    private javax.swing.JLabel cardNum_lbl;
    private javax.swing.JTextField cardNum_txt;
    private javax.swing.JLabel cvc_lbl;
    private javax.swing.JTextField cvc_txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel subTot_lbl;
    private javax.swing.JLabel totCost_lbl;
    // End of variables declaration//GEN-END:variables
}
