/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Package;

import Account_Package.Customer;
import Database_Package.DBConnectivity;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author umahm, Kimberly Eslami
 * @version (06/04/18) version 3
 * @since (26/03/18) version 1
 */
public class CustomerAccount extends javax.swing.JFrame {
    /** The Employees ID. */
    private final String empID;
    /** The Employee job role. */
    private final String jobRole;
    /** The Customer ID. */
    String custID;

    /**
     * Creates new form CustomerAccount.
     *
     * @param jobRole employees job role
     */
    public CustomerAccount(String jobRole, String empID) {
        this.empID = empID;
        this.jobRole = jobRole;
        initComponents();
        DBConnectivity myDB = new DBConnectivity();
        Random rand = new Random();
        custID = "ACC" + String.format("%04d", rand.nextInt(10000) + 1);
        myDB.connect();
        Connection con = myDB.getConn();
        try {
            con.setAutoCommit(false);

            boolean isDuplicate = true;
            while (isDuplicate) {
                ResultSet rs = myDB.read("SELECT customer_ID FROM Customers WHERE customer_ID = '" + custID + "'");
                try {
                    if (!rs.next()) {
                        isDuplicate = false;
                    } else {
                        custID = "ACC" + String.format("%04d", rand.nextInt(10000) + 1);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            CustomerID_lbl.setText("Customer ID: " + custID);
            con.commit();
        }catch (SQLException ex) {
            if (con != null) {
                try {
                    System.err.print("Transaction rolling back!");
                    con.rollback();
                } catch (SQLException ex1) {
                    Logger.getLogger(DBConnectivity.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }
        }finally{
            try {
                con.setAutoCommit(true);
            } catch (SQLException ex) {
                Logger.getLogger(CustomerAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
            myDB.closeConnection();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back_btn = new javax.swing.JButton();
        Register_btn = new javax.swing.JButton();
        PostCode_lbl = new javax.swing.JLabel();
        PostCode_txt = new javax.swing.JTextField();
        Country_txt = new javax.swing.JTextField();
        Country_lbl = new javax.swing.JLabel();
        City_lbl = new javax.swing.JLabel();
        City_txt = new javax.swing.JTextField();
        Email_lbl = new javax.swing.JLabel();
        Email_txt = new javax.swing.JTextField();
        PhoneNumber_txt = new javax.swing.JTextField();
        PhoneNumber_lbl = new javax.swing.JLabel();
        Address_scrl = new javax.swing.JScrollPane();
        Address_txt = new javax.swing.JTextArea();
        Address_lbl = new javax.swing.JLabel();
        Surname_txt = new javax.swing.JTextField();
        Surname_lbl = new javax.swing.JLabel();
        FirstName_lbl = new javax.swing.JLabel();
        FirstName_txt = new javax.swing.JTextField();
        CustomerID_lbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CreateCustomer_lbl = new javax.swing.JLabel();
        HomePage_btn = new javax.swing.JButton();
        LogOut_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Back_btn.setBackground(new java.awt.Color(0, 153, 255));
        Back_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Back_btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn.setText("Back");
        Back_btn.setBorder(null);
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        Register_btn.setBackground(new java.awt.Color(0, 153, 255));
        Register_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Register_btn.setForeground(new java.awt.Color(255, 255, 255));
        Register_btn.setText("Register");
        Register_btn.setBorder(null);
        Register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_btnActionPerformed(evt);
            }
        });

        PostCode_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PostCode_lbl.setText("Post Code:");

        PostCode_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        Country_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Country_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Country_txtKeyTyped(evt);
            }
        });

        Country_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Country_lbl.setText("Country:");

        City_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        City_lbl.setText("City:");

        City_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        City_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                City_txtKeyTyped(evt);
            }
        });

        Email_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Email_lbl.setText("Email:");

        Email_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        PhoneNumber_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        PhoneNumber_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumber_txtActionPerformed(evt);
            }
        });
        PhoneNumber_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhoneNumber_txtKeyTyped(evt);
            }
        });

        PhoneNumber_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PhoneNumber_lbl.setText("Phone Number:");

        Address_scrl.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Address_txt.setColumns(20);
        Address_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Address_txt.setRows(5);
        Address_scrl.setViewportView(Address_txt);

        Address_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Address_lbl.setText("Address:");

        Surname_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Surname_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Surname_txtKeyTyped(evt);
            }
        });

        Surname_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Surname_lbl.setText("Surname:");

        FirstName_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        FirstName_lbl.setText("First Name:");

        FirstName_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        FirstName_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FirstName_txtKeyTyped(evt);
            }
        });

        CustomerID_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        CustomerID_lbl.setText("Customer ID:");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        CreateCustomer_lbl.setBackground(new java.awt.Color(0, 153, 255));
        CreateCustomer_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        CreateCustomer_lbl.setForeground(new java.awt.Color(255, 255, 255));
        CreateCustomer_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateCustomer_lbl.setText("Create Customer");
        CreateCustomer_lbl.setOpaque(true);

        HomePage_btn.setBackground(new java.awt.Color(255, 255, 255));
        HomePage_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        HomePage_btn.setForeground(new java.awt.Color(0, 153, 255));
        HomePage_btn.setText("Home Page");
        HomePage_btn.setBorder(null);
        HomePage_btn.setMaximumSize(new java.awt.Dimension(65, 19));
        HomePage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePage_btnActionPerformed(evt);
            }
        });

        LogOut_btn.setBackground(new java.awt.Color(255, 255, 255));
        LogOut_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        LogOut_btn.setForeground(new java.awt.Color(0, 153, 255));
        LogOut_btn.setText("Logout");
        LogOut_btn.setBorder(null);
        LogOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOut_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomePage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(CreateCustomer_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomePage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateCustomer_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(FirstName_lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FirstName_txt))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Surname_lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Surname_txt))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PhoneNumber_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PhoneNumber_txt))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(93, Short.MAX_VALUE)
                                .addComponent(Email_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(CustomerID_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PostCode_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Country_lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Country_txt)
                            .addComponent(PostCode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(City_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(City_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Address_lbl)
                        .addComponent(Address_scrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(Register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerID_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Address_scrl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstName_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Surname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Surname_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNumber_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(City_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(City_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Country_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Country_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PostCode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PostCode_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Logout Button
     * <p>
     * Closes the form and takes you back to the login form
     */
    private void LogOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_btnActionPerformed

        this.dispose();
        Login_Form l = new Login_Form();
        l.setVisible(true);
    }//GEN-LAST:event_LogOut_btnActionPerformed
    /**
     * HomePage Button
     * <p>
     * Closes the form and takes you back to the home page form.
     */
    private void HomePage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePage_btnActionPerformed

        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_HomePage_btnActionPerformed

    private void PhoneNumber_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumber_txtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_PhoneNumber_txtActionPerformed
    /**
     * Back
     * <p>
     * Closes the form taking you back to the previous form.
     */
    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed

        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);

    }//GEN-LAST:event_Back_btnActionPerformed
    /**
     * Phone Number text field restriction
     * <p>
     * Restricts the field to only allows 11 numbers to be entered.
     */
    private void PhoneNumber_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneNumber_txtKeyTyped

        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }

        if (PhoneNumber_txt.getText().length() >= 11) {
            evt.consume();
        }

    }//GEN-LAST:event_PhoneNumber_txtKeyTyped
    /**
     * First name text field restriction
     * <p>
     * Restricts the field to only allows characters to be entered.
     */
    private void FirstName_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstName_txtKeyTyped

        char vChar = evt.getKeyChar();
        if ((Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_FirstName_txtKeyTyped
    /**
     * Surname text field restriction
     * <p>
     * Restricts the field to only allows characters to be entered.
     */
    private void Surname_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Surname_txtKeyTyped

        char vChar = evt.getKeyChar();
        if ((Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_Surname_txtKeyTyped
    /**
     * City text field restriction
     * <p>
     * Restricts the field to only allows characters to be entered.
     */
    private void City_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_City_txtKeyTyped

        char vChar = evt.getKeyChar();
        if ((Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_City_txtKeyTyped
    /**
     * Country text field restriction
     * <p>
     * Restricts the field to only allows characters to be entered.
     */
    private void Country_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Country_txtKeyTyped

        char vChar = evt.getKeyChar();
        if ((Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_Country_txtKeyTyped
    /**
     * Register Customer
     * <p>
     * Creates a new Customer and stores it in the database
     */
    private void Register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_btnActionPerformed

        if (FirstName_txt.getText().isEmpty() && Surname_txt.getText().isEmpty() && PhoneNumber_txt.getText().isEmpty() && Email_txt.getText().isEmpty() && Address_txt.getText().isEmpty() && City_txt.getText().isEmpty() && Country_txt.getText().isEmpty() && PostCode_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Text in All Fields ");
        } else {
            Customer Customer = new Customer(custID, FirstName_txt.getText(), Surname_txt.getText(), Address_txt.getText(), City_txt.getText(),
                    Country_txt.getText(), PostCode_txt.getText(), Email_txt.getText(), PhoneNumber_txt.getText());
            JOptionPane.showMessageDialog(null, "Customer Registered ");
            this.dispose();
            HomePage hp = new HomePage(jobRole, empID);
            hp.setVisible(true);

        }
    }//GEN-LAST:event_Register_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerAccount("Office Manager", "FG12").setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_lbl;
    private javax.swing.JScrollPane Address_scrl;
    private javax.swing.JTextArea Address_txt;
    private javax.swing.JButton Back_btn;
    private javax.swing.JLabel City_lbl;
    private javax.swing.JTextField City_txt;
    private javax.swing.JLabel Country_lbl;
    private javax.swing.JTextField Country_txt;
    private javax.swing.JLabel CreateCustomer_lbl;
    private javax.swing.JLabel CustomerID_lbl;
    private javax.swing.JLabel Email_lbl;
    private javax.swing.JTextField Email_txt;
    private javax.swing.JLabel FirstName_lbl;
    private javax.swing.JTextField FirstName_txt;
    private javax.swing.JButton HomePage_btn;
    private javax.swing.JButton LogOut_btn;
    private javax.swing.JLabel PhoneNumber_lbl;
    private javax.swing.JTextField PhoneNumber_txt;
    private javax.swing.JLabel PostCode_lbl;
    private javax.swing.JTextField PostCode_txt;
    private javax.swing.JButton Register_btn;
    private javax.swing.JLabel Surname_lbl;
    private javax.swing.JTextField Surname_txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
