/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Package;

import Account_Package.Employee;
import Database_Package.DBConnectivity;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author umahm, Kimberly Eslami
 * @version (06/04/18) Version 2
 * @since (29/03/18) Version 1
 */
public class EmployeeAccount extends javax.swing.JFrame {

    /** The Employee ID */
    private String empID;

    /**
     * Creates new form EmployeeAccount.
     * @throws java.sql.SQLException
     */
    public EmployeeAccount() throws SQLException {

        initComponents();

        DBConnectivity myDB = new DBConnectivity();
        myDB.connect();
        
        Connection con = myDB.getConn();
        try {
            con.setAutoCommit(false);

            ResultSet rs = myDB.read("SELECT employee_ID FROM employee");
            Random rand = new Random();
            String letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            String numbers = "0123456789";
            String randomString = "";
            int letterLength = 2;
            int numLength = 2;
            boolean idTaken;
            do {
                idTaken = false;
                //add random letters to array
                char[] randomLetters = new char[letterLength];
                for (int i = 0; i < letterLength; i++) {
                    randomLetters[i] = letters.charAt(rand.nextInt(letters.length()));
                }
                //add random numbers to array
                char[] randomNumbers = new char[numLength];
                for (int i = 0; i < numLength; i++) {
                    randomNumbers[i] = numbers.charAt(rand.nextInt(randomNumbers.length));
                }
                //Add letters to string
                for (int i = 0; i < randomLetters.length; i++) {
                    randomString += randomLetters[i];
                }
                //add numbers to string
                for (int i = 0; i < randomNumbers.length; i++) {
                    randomString += randomNumbers[i];
                }
                //set string as employee id
                empID = randomString;
                //checks database for id.
                while (rs.next()) {
                    if (rs.getString("employee_ID").equals(empID)) {
                        idTaken = true;
                    }
                }
                EmployeeID_lbl.setText("Employee ID: " + empID);
            } while (idTaken); //loops if id is taken
        con.commit();
        }catch (SQLException ex) {
            if (con != null) {
                try {
                    System.err.print("Transaction rolling back!");
                    con.rollback();
                } catch (SQLException ex1) {
                    Logger.getLogger(DBConnectivity.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }
        }finally{
            con.setAutoCommit(true);
            myDB.closeConnection();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Register_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        Answer_txt = new javax.swing.JTextField();
        SecurityQuestion_lbl = new javax.swing.JLabel();
        SelectSecurityQuestion_lbl = new javax.swing.JLabel();
        SecurityQuestion_cmbo = new javax.swing.JComboBox<>();
        PostCode_lbl = new javax.swing.JLabel();
        PostCode_txt = new javax.swing.JTextField();
        County_lbl = new javax.swing.JLabel();
        Country_txt = new javax.swing.JTextField();
        City_lbl = new javax.swing.JLabel();
        City_txt = new javax.swing.JTextField();
        Address_scrl = new javax.swing.JScrollPane();
        Address_txt = new javax.swing.JTextArea();
        Email_lbl1 = new javax.swing.JLabel();
        Password_txt = new javax.swing.JPasswordField();
        Email_lbl = new javax.swing.JLabel();
        Email_txt = new javax.swing.JTextField();
        PhoneNumber_lbl = new javax.swing.JLabel();
        Surname_lbl = new javax.swing.JLabel();
        FirstName_lbl = new javax.swing.JLabel();
        FirstName_txt = new javax.swing.JTextField();
        Surname_txt = new javax.swing.JTextField();
        PhoneNumber_txt = new javax.swing.JTextField();
        Address_lbl1 = new javax.swing.JLabel();
        Address_lbl = new javax.swing.JLabel();
        Role_cmbo = new javax.swing.JComboBox<>();
        EmployeeID_lbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CreateEmployee_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Register_btn.setBackground(new java.awt.Color(0, 153, 255));
        Register_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Register_btn.setForeground(new java.awt.Color(255, 255, 255));
        Register_btn.setText("Register");
        Register_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Register_btn.setContentAreaFilled(false);
        Register_btn.setOpaque(true);
        Register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_btnActionPerformed(evt);
            }
        });

        Back_btn.setBackground(new java.awt.Color(0, 153, 255));
        Back_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Back_btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn.setText("Back");
        Back_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back_btn.setContentAreaFilled(false);
        Back_btn.setOpaque(true);
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        Answer_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Answer_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer_txtActionPerformed(evt);
            }
        });
        Answer_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Answer_txtKeyTyped(evt);
            }
        });

        SecurityQuestion_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        SecurityQuestion_lbl.setText("<html>\nSecurity Question\n<br> \nAnswer: \n</html>");

        SelectSecurityQuestion_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        SelectSecurityQuestion_lbl.setText("<html>\nSelect Security <br> \nQuestion: \n</html>");

        SecurityQuestion_cmbo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        SecurityQuestion_cmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "What is your mothers maiden name?", "What is your pets name?", "What was your childhood nickname?", " ", " ", " " }));
        SecurityQuestion_cmbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecurityQuestion_cmboActionPerformed(evt);
            }
        });

        PostCode_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PostCode_lbl.setText("Post Code:");

        PostCode_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        County_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        County_lbl.setText("Country:");

        Country_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Country_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Country_txtKeyTyped(evt);
            }
        });

        City_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        City_lbl.setText("City:");

        City_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        City_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                City_txtActionPerformed(evt);
            }
        });
        City_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                City_txtKeyTyped(evt);
            }
        });

        Address_scrl.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Address_txt.setColumns(20);
        Address_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Address_txt.setRows(5);
        Address_scrl.setViewportView(Address_txt);

        Email_lbl1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Email_lbl1.setText("Password:");

        Password_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        Email_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Email_lbl.setText("Email:");

        Email_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        PhoneNumber_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PhoneNumber_lbl.setText("Phone Number:");

        Surname_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Surname_lbl.setText("Surname:");

        FirstName_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        FirstName_lbl.setText("First Name:");

        FirstName_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        FirstName_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FirstName_txtKeyTyped(evt);
            }
        });

        Surname_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Surname_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Surname_txtKeyTyped(evt);
            }
        });

        PhoneNumber_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        PhoneNumber_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhoneNumber_txtKeyTyped(evt);
            }
        });

        Address_lbl1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Address_lbl1.setText("Address:");

        Address_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Address_lbl.setText("Position:");

        Role_cmbo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Role_cmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Technician", "Receptionist", "Office Manager", "Shift Manager", " ", " " }));

        EmployeeID_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        EmployeeID_lbl.setText("Employee ID:");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        CreateEmployee_lbl.setBackground(new java.awt.Color(0, 153, 255));
        CreateEmployee_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        CreateEmployee_lbl.setForeground(new java.awt.Color(255, 255, 255));
        CreateEmployee_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateEmployee_lbl.setText("Create Employee");
        CreateEmployee_lbl.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(CreateEmployee_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(CreateEmployee_lbl)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(Register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addComponent(Address_scrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Address_lbl1)
                                        .addComponent(Address_lbl))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Role_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(County_lbl)
                                    .addComponent(City_lbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(City_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Country_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PostCode_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PostCode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Surname_lbl)
                            .addComponent(FirstName_lbl)
                            .addComponent(EmployeeID_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FirstName_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(Surname_txt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(PhoneNumber_lbl)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Email_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Email_lbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SelectSecurityQuestion_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SecurityQuestion_cmbo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNumber_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SecurityQuestion_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Answer_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(427, 427, 427))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(Role_cmbo)
                    .addComponent(Address_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmployeeID_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FirstName_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FirstName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Address_lbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Address_scrl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Surname_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Surname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNumber_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SelectSecurityQuestion_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SecurityQuestion_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SecurityQuestion_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Answer_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(City_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(City_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Country_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(County_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PostCode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PostCode_lbl))))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Answer_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Answer_txtActionPerformed
    /**
     * First name text field restriction
     * <p>
     * Restricts the field to only allows characters to be entered. 
     */
    private void FirstName_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstName_txtKeyTyped

        char vChar = evt.getKeyChar();
        if ((Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_FirstName_txtKeyTyped
     /**
     * Surname text field restriction
     * <p>
     * Restricts the field to only allows characters to be entered. 
     */
    private void Surname_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Surname_txtKeyTyped

        char vChar = evt.getKeyChar();
        if ((Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_Surname_txtKeyTyped
    /**
     *City text field restriction
     * <p>
     * Restricts the field to only allows characters to be entered. 
     */
    private void City_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_City_txtKeyTyped

        char vChar = evt.getKeyChar();
        if ((Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_City_txtKeyTyped
    /**
     * Country text field restriction
     * <p>
     * Restricts the field to only allows characters to be entered. 
     */
    private void Country_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Country_txtKeyTyped

        char vChar = evt.getKeyChar();
        if ((Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_Country_txtKeyTyped
     /**
     *Phone Number text field restriction
     * <p>
     * Restricts the field to only allows 11 numbers to be entered. 
     */
    private void PhoneNumber_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneNumber_txtKeyTyped

        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }

        if (PhoneNumber_txt.getText().length() >= 11) {
            evt.consume();
        }
    }//GEN-LAST:event_PhoneNumber_txtKeyTyped
    /** Register Employee
     * <p>
     * Creates a new employee and stores it in the database
     */
    private void Register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_btnActionPerformed

        String pass = new String(Password_txt.getPassword());
        if (FirstName_txt.getText().isEmpty() && Surname_txt.getText().isEmpty() && PhoneNumber_txt.getText().isEmpty() && Email_txt.getText().isEmpty() && Answer_txt.getText().isEmpty() && Address_txt.getText().isEmpty() && City_txt.getText().isEmpty() && Country_txt.getText().isEmpty() && PostCode_txt.getText().isEmpty() && Role_cmbo.getSelectedItem().toString().isEmpty() && SecurityQuestion_cmbo.getSelectedItem().toString().isEmpty() && Answer_txt.getText().isEmpty() && pass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter All Fields ");
        } else {
            Employee employee = new Employee(empID, FirstName_txt.getText(), Surname_txt.getText(), Address_txt.getText(), City_txt.getText(),
                    Country_txt.getText(), PostCode_txt.getText(), Email_txt.getText(), PhoneNumber_txt.getText(),
                    Role_cmbo.getSelectedItem().toString(), SecurityQuestion_cmbo.getSelectedItem().toString(), Answer_txt.getText(), pass);
            JOptionPane.showMessageDialog(null, "Employee Registered ");
            this.dispose();
            Login_Form l = new Login_Form();
            l.setVisible(true);

        }

    }//GEN-LAST:event_Register_btnActionPerformed
    /** Back button
     * <p>
     * Closes the form taking you back to the previous form
     */
    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed

        this.dispose();
        
    }//GEN-LAST:event_Back_btnActionPerformed

     /**
     *Answer text field restriction
     * <p>
     * Restricts the field to only allows characters to be entered. 
     */
    private void Answer_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Answer_txtKeyTyped

        char vChar = evt.getKeyChar();
        if ((Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_Answer_txtKeyTyped

    private void SecurityQuestion_cmboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecurityQuestion_cmboActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_SecurityQuestion_cmboActionPerformed

    private void City_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_City_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_City_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccount.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EmployeeAccount().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EmployeeAccount.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address_lbl;
    private javax.swing.JLabel Address_lbl1;
    private javax.swing.JScrollPane Address_scrl;
    private javax.swing.JTextArea Address_txt;
    private javax.swing.JTextField Answer_txt;
    private javax.swing.JButton Back_btn;
    private javax.swing.JLabel City_lbl;
    private javax.swing.JTextField City_txt;
    private javax.swing.JTextField Country_txt;
    private javax.swing.JLabel County_lbl;
    private javax.swing.JLabel CreateEmployee_lbl;
    private javax.swing.JLabel Email_lbl;
    private javax.swing.JLabel Email_lbl1;
    private javax.swing.JTextField Email_txt;
    private javax.swing.JLabel EmployeeID_lbl;
    private javax.swing.JLabel FirstName_lbl;
    private javax.swing.JTextField FirstName_txt;
    private javax.swing.JPasswordField Password_txt;
    private javax.swing.JLabel PhoneNumber_lbl;
    private javax.swing.JTextField PhoneNumber_txt;
    private javax.swing.JLabel PostCode_lbl;
    private javax.swing.JTextField PostCode_txt;
    private javax.swing.JButton Register_btn;
    private javax.swing.JComboBox<String> Role_cmbo;
    private javax.swing.JComboBox<String> SecurityQuestion_cmbo;
    private javax.swing.JLabel SecurityQuestion_lbl;
    private javax.swing.JLabel SelectSecurityQuestion_lbl;
    private javax.swing.JLabel Surname_lbl;
    private javax.swing.JTextField Surname_txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
