/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI_Package;

import Account_Package.Customer;
import Account_Package.DiscountBand;
import Account_Package.FlexibleDiscount;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author umahm
 */
public class FlexibleDiscountForm extends javax.swing.JFrame {
    /** The Employee job role. */
    private final String jobRole;
    /** The Customer that the discount is applied to. */
    private Customer cust; 
    /** ArrayList with the list of discount bands. */
    private ArrayList<DiscountBand> bands = new ArrayList<>();
    /** The Employees ID. */
    private final String empID;
    
    /** Creates new form FlexibleDiscount.
     * 
     * @param jobRole The Employee job role.
     * @param cust  Customer the discount is being applied to.
     * @param empID The employee ID.
     */
    public FlexibleDiscountForm(String jobRole, Customer cust, String empID) {
        this.empID = empID;
        this.jobRole = jobRole;
        this.cust = cust;
        initComponents();
        CustomerID_Label.setText("Customer ID: " + cust.getCustID());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Delete_Button = new javax.swing.JButton();
        Assign_Button = new javax.swing.JButton();
        Back_Button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlexibleDiscount_Table = new javax.swing.JTable();
        DiscountRate_Label = new javax.swing.JLabel();
        DiscountRate_Field = new javax.swing.JTextField();
        Add_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Upper_Limit_Field = new javax.swing.JTextField();
        Volume_Label = new javax.swing.JLabel();
        Lower_Limit_Field = new javax.swing.JTextField();
        ListOfBands_Label = new javax.swing.JLabel();
        CustomerID_Label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Logout_Button = new javax.swing.JButton();
        HomePage_Button = new javax.swing.JButton();
        FlexibleDiscount_Field = new javax.swing.JTextField();
        LOGO_Label = new javax.swing.JLabel();
        fixedBands_cmbo = new javax.swing.JComboBox<>();
        fixedBand_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Delete_Button.setBackground(new java.awt.Color(0, 153, 255));
        Delete_Button.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Delete_Button.setForeground(new java.awt.Color(255, 255, 255));
        Delete_Button.setText("Delete");
        Delete_Button.setBorder(null);
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });

        Assign_Button.setBackground(new java.awt.Color(0, 153, 255));
        Assign_Button.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Assign_Button.setForeground(new java.awt.Color(255, 255, 255));
        Assign_Button.setText("Assign");
        Assign_Button.setBorder(null);
        Assign_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assign_ButtonActionPerformed(evt);
            }
        });

        Back_Button.setBackground(new java.awt.Color(0, 153, 255));
        Back_Button.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Back_Button.setForeground(new java.awt.Color(255, 255, 255));
        Back_Button.setText("Back");
        Back_Button.setBorder(null);
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        FlexibleDiscount_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Volume", "Discount"
            }
        ));
        jScrollPane2.setViewportView(FlexibleDiscount_Table);

        DiscountRate_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        DiscountRate_Label.setText("Discount Rate:");

        Add_Button.setBackground(new java.awt.Color(0, 153, 255));
        Add_Button.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Add_Button.setForeground(new java.awt.Color(255, 255, 255));
        Add_Button.setText("Add");
        Add_Button.setContentAreaFilled(false);
        Add_Button.setOpaque(true);
        Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setText("Upper Limit:");

        Volume_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Volume_Label.setText("Lower Limit:");

        ListOfBands_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        ListOfBands_Label.setText("List of Bands:");

        CustomerID_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        CustomerID_Label.setText("Customer ID:");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        Logout_Button.setBackground(new java.awt.Color(255, 255, 255));
        Logout_Button.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Logout_Button.setForeground(new java.awt.Color(0, 153, 255));
        Logout_Button.setText("Logout");
        Logout_Button.setBorder(null);
        Logout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_ButtonActionPerformed(evt);
            }
        });

        HomePage_Button.setBackground(new java.awt.Color(255, 255, 255));
        HomePage_Button.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        HomePage_Button.setForeground(new java.awt.Color(0, 153, 255));
        HomePage_Button.setText("Home Page");
        HomePage_Button.setBorder(null);
        HomePage_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePage_ButtonActionPerformed(evt);
            }
        });

        FlexibleDiscount_Field.setBackground(new java.awt.Color(0, 153, 255));
        FlexibleDiscount_Field.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        FlexibleDiscount_Field.setForeground(new java.awt.Color(255, 255, 255));
        FlexibleDiscount_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FlexibleDiscount_Field.setText("Flexible Discount");
        FlexibleDiscount_Field.setBorder(null);
        FlexibleDiscount_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlexibleDiscount_FieldActionPerformed(evt);
            }
        });

        LOGO_Label.setText("LOGO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOGO_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Logout_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HomePage_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(FlexibleDiscount_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Logout_Button)
                            .addComponent(HomePage_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FlexibleDiscount_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(LOGO_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fixedBands_cmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "<= 1000", "1000 - 2000", "> 2000" }));

        fixedBand_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        fixedBand_lbl.setText("Fixed Bands:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(Assign_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ListOfBands_Label)
                            .addComponent(CustomerID_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Volume_Label)
                            .addComponent(DiscountRate_Label)
                            .addComponent(jLabel1)
                            .addComponent(fixedBand_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fixedBands_cmbo, 0, 1, Short.MAX_VALUE)
                            .addComponent(DiscountRate_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(Upper_Limit_Field)
                            .addComponent(Lower_Limit_Field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CustomerID_Label)
                        .addGap(36, 36, 36)
                        .addComponent(ListOfBands_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fixedBands_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fixedBand_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Volume_Label)
                            .addComponent(Lower_Limit_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Upper_Limit_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DiscountRate_Label)
                                    .addComponent(DiscountRate_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Add_Button)
                                .addGap(4, 4, 4)))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete_Button)
                    .addComponent(Assign_Button)
                    .addComponent(Back_Button))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FlexibleDiscount_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlexibleDiscount_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlexibleDiscount_FieldActionPerformed
    /**
     * Logout Button
     * <p>
     * Closes the form and takes you back to the login form.
     */
    private void Logout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_ButtonActionPerformed
        Login_Form lf = new Login_Form();
        lf.setVisible(true);
    }//GEN-LAST:event_Logout_ButtonActionPerformed
    /**
     * Back Button
     * <p>
     * Closes the form taking you back to the previous form.
     */
    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        this.dispose();
        AssignDiscountPlan adp = new AssignDiscountPlan(jobRole, cust, empID);
        adp.setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed
    /**
     * Assign Button
     * <p>
     * Assigns the discount plan to the customer.
     */
    private void Assign_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assign_ButtonActionPerformed
        try {
            new FlexibleDiscount(bands, cust.getCustID());
            this.dispose();
            AssignDiscountPlan adp = new AssignDiscountPlan(jobRole, cust, empID);
            adp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FlexibleDiscountForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Assign_ButtonActionPerformed
    /**
     * HomePage Button
     * <p>
     * Closes the form and takes you back to the home page form.
     */
    private void HomePage_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePage_ButtonActionPerformed
        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_HomePage_ButtonActionPerformed
    /**
     * Add Button
     * <p>
     * Adds a new Discount Band to the table.
     */
    private void Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ButtonActionPerformed
        if(fixedBands_cmbo.getSelectedIndex() == 0 && !(Lower_Limit_Field.getText().isEmpty()) && !(Upper_Limit_Field.getText().isEmpty())){
            if (DiscountRate_Field.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please enter discount rate!", "Error!", JOptionPane.ERROR_MESSAGE);
            } else {
                bands.add(new DiscountBand(Integer.parseInt(Lower_Limit_Field.getText()),
                        Integer.parseInt(Upper_Limit_Field.getText()),Double.parseDouble(DiscountRate_Field.getText())));
            }
        } else if (!(fixedBands_cmbo.getSelectedIndex() == 0) && Lower_Limit_Field.getText().isEmpty() && Upper_Limit_Field.getText().isEmpty()){
            if (DiscountRate_Field.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please enter discount rate!", "Error!", JOptionPane.ERROR_MESSAGE);
            } else {
                if(fixedBands_cmbo.getSelectedIndex() == 1){
                    bands.add(new DiscountBand(0,1000,Double.parseDouble(DiscountRate_Field.getText())));
                } else if (fixedBands_cmbo.getSelectedIndex() == 2){
                    bands.add(new DiscountBand(1000,2000,Double.parseDouble(DiscountRate_Field.getText())));
                } else {
                    bands.add(new DiscountBand(2000,9999999,Double.parseDouble(DiscountRate_Field.getText())));
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter or select a Discount Band!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        DefaultTableModel dtm = (DefaultTableModel) FlexibleDiscount_Table.getModel();
        dtm.setRowCount(0);
        for (DiscountBand band : bands){
            Object[] object = {band.getLowerLimit() + "-" + band.getUpperLimit(), band.getDiscountRate()};
            dtm.addRow(object);
        }
    }//GEN-LAST:event_Add_ButtonActionPerformed
     /**
     * Remove Button
     * <p>
     * Removed a Discount Band from the table.
     */
    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ButtonActionPerformed
        int row = FlexibleDiscount_Table.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(null, "Please select a Discount Band!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel dtm = (DefaultTableModel) FlexibleDiscount_Table.getModel();
            for (int i = 0; i < bands.size(); i++){
                if(bands.get(i).getLowerLimit() == Integer.parseInt(dtm.getValueAt(row, 0).toString().split("-")[0]) 
                        && bands.get(i).getUpperLimit() == Integer.parseInt(dtm.getValueAt(row, 0).toString().split("-")[1])
                        && bands.get(i).getDiscountRate() == Double.parseDouble(dtm.getValueAt(row, 1).toString())){
                    bands.remove(i);
                }
            }
            dtm.removeRow(row);
        }
    }//GEN-LAST:event_Delete_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlexibleDiscountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlexibleDiscountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlexibleDiscountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlexibleDiscountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlexibleDiscountForm("Office Manager", new Customer("ACC0002"), "FG12").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Button;
    private javax.swing.JButton Assign_Button;
    private javax.swing.JButton Back_Button;
    private javax.swing.JLabel CustomerID_Label;
    private javax.swing.JButton Delete_Button;
    private javax.swing.JTextField DiscountRate_Field;
    private javax.swing.JLabel DiscountRate_Label;
    private javax.swing.JTextField FlexibleDiscount_Field;
    private javax.swing.JTable FlexibleDiscount_Table;
    private javax.swing.JButton HomePage_Button;
    private javax.swing.JLabel LOGO_Label;
    private javax.swing.JLabel ListOfBands_Label;
    private javax.swing.JButton Logout_Button;
    private javax.swing.JTextField Lower_Limit_Field;
    private javax.swing.JTextField Upper_Limit_Field;
    private javax.swing.JLabel Volume_Label;
    private javax.swing.JLabel fixedBand_lbl;
    private javax.swing.JComboBox<String> fixedBands_cmbo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
