/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Package;

/**
 *
 * @author Allen
 */
public class Generate_Report extends javax.swing.JFrame {
    /** The Employee job role. */
    private final String jobRole;
    /** The Employees ID. */
    private final String empID;

    /**
     * Creates new form Generate_Report
     * 
     * @param jobRole employee's job role
     * @param empID The employee ID.
     */
    public Generate_Report(String jobRole, String empID) {
        this.empID = empID;
        this.jobRole = jobRole;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        SelectReport_Label = new javax.swing.JLabel();
        StartDate_Field = new javax.swing.JLabel();
        EndDate_Field = new javax.swing.JLabel();
        coboxSelectReport = new javax.swing.JComboBox<>();
        DateStartDate = new com.toedter.calendar.JDateChooser();
        DateEndDate = new com.toedter.calendar.JDateChooser();
        btnGenerate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        CustomerID_Label = new javax.swing.JLabel();
        CustID_Field = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        GenerateReport_Field = new javax.swing.JTextField();
        btnLogOut = new javax.swing.JButton();
        btnHomePage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 475));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        SelectReport_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        SelectReport_Label.setText("Select Report:");
        SelectReport_Label.setToolTipText("");

        StartDate_Field.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        StartDate_Field.setText("Start Date:");
        StartDate_Field.setToolTipText("");

        EndDate_Field.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        EndDate_Field.setText("End Date:");
        EndDate_Field.setToolTipText("");

        coboxSelectReport.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        coboxSelectReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None","Individual Report", "Individual Performance Report", "Summary Performance Report"}));
        coboxSelectReport.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                coboxSelectReportItemStateChanged(evt);
            }
        });
        coboxSelectReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coboxSelectReportActionPerformed(evt);
            }
        });

        DateStartDate.setDateFormatString("yyyy-MM-dd");
        DateStartDate.setEnabled(false);

        DateEndDate.setDateFormatString("yyyy-MM-dd");
        DateEndDate.setEnabled(false);

        btnGenerate.setBackground(new java.awt.Color(0, 153, 255));
        btnGenerate.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnGenerate.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerate.setText("Generate");
        btnGenerate.setToolTipText("");
        btnGenerate.setBorder(null);
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        CustomerID_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        CustomerID_Label.setText("Customer ID:");

        CustID_Field.setEnabled(false);
        CustID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustID_FieldActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel10.setText("LOGO");

        GenerateReport_Field.setBackground(new java.awt.Color(0, 153, 255));
        GenerateReport_Field.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        GenerateReport_Field.setForeground(new java.awt.Color(255, 255, 255));
        GenerateReport_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GenerateReport_Field.setText("Generate Report");
        GenerateReport_Field.setToolTipText("");
        GenerateReport_Field.setBorder(null);
        GenerateReport_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReport_FieldActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(0, 153, 255));
        btnLogOut.setText("Logout");
        btnLogOut.setBorder(null);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnHomePage.setBackground(new java.awt.Color(255, 255, 255));
        btnHomePage.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnHomePage.setForeground(new java.awt.Color(0, 153, 255));
        btnHomePage.setText("Home Page");
        btnHomePage.setBorder(null);
        btnHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(GenerateReport_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut)
                    .addComponent(btnHomePage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenerateReport_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartDate_Field)
                    .addComponent(EndDate_Field)
                    .addComponent(CustomerID_Label)
                    .addComponent(SelectReport_Label))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coboxSelectReport, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DateStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DateEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(187, 187, 187))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectReport_Label)
                    .addComponent(coboxSelectReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartDate_Field)
                    .addComponent(DateStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EndDate_Field)
                    .addComponent(DateEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerID_Label)
                    .addComponent(CustID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerate)
                    .addComponent(btnBack))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateReport_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReport_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateReport_FieldActionPerformed
    /**
     * Logout Button
     * <p>
     * Closes the form and takes you back to the login form.
     */
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        Login_Form lf = new Login_Form();
        lf.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed
     /**
     * Generate Button
     * <p>
     * Generates the Reports.
     */
    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        String report = coboxSelectReport.getSelectedItem().toString();
        if(report.equals("Individual Report")){
            IndividualReportForm ir = new IndividualReportForm(this, jobRole, CustID_Field.getText(), 
                    new java.sql.Date(DateStartDate.getDate().getTime()), new java.sql.Date(DateEndDate.getDate().getTime()), empID);
            ir.setVisible(true);
        } else if(report.equals("Individual Performance Report")){
            IndividualPerformanceReportForm ipr = new IndividualPerformanceReportForm(this, jobRole, 
                    new java.sql.Date(DateStartDate.getDate().getTime()), new java.sql.Date(DateEndDate.getDate().getTime()), empID);
            ipr.setVisible(true);
        } else {
            SummaryPerformanceReportForm spr = new SummaryPerformanceReportForm(this, jobRole, 
                    new java.sql.Date(DateStartDate.getDate().getTime()), new java.sql.Date(DateEndDate.getDate().getTime()), empID);
            spr.setVisible(true);
        }
    }//GEN-LAST:event_btnGenerateActionPerformed
      /**
     * Back Button
     * <p>
     * Closes the form taking you back to the previous form.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void coboxSelectReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coboxSelectReportActionPerformed

    }//GEN-LAST:event_coboxSelectReportActionPerformed

    private void CustID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustID_FieldActionPerformed

    }//GEN-LAST:event_CustID_FieldActionPerformed
     /** Select report items
      * <p>
      * Sets the text field to visible when individual report is selected.
      */
    private void coboxSelectReportItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_coboxSelectReportItemStateChanged
        String s = coboxSelectReport.getSelectedItem().toString();
        if (s.equals("None")){
            DateStartDate.setEnabled(false);
            DateEndDate.setEnabled(false);
            CustID_Field.setEnabled(false);
        }else if (s.equals("Individual Report")){
            DateStartDate.setEnabled(true);
            DateEndDate.setEnabled(true);
            CustID_Field.setEnabled(true);
        } else {
            DateStartDate.setEnabled(true);
            DateEndDate.setEnabled(true);
            CustID_Field.setEnabled(false);
        }
    }//GEN-LAST:event_coboxSelectReportItemStateChanged
     /**
     * HomePage Button
     * <p>
     * Closes the form and takes you back to the home page form.
     */
    private void btnHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePageActionPerformed
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_btnHomePageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generate_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generate_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generate_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generate_Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generate_Report("Office Manager", "FG12").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustID_Field;
    private javax.swing.JLabel CustomerID_Label;
    private com.toedter.calendar.JDateChooser DateEndDate;
    private com.toedter.calendar.JDateChooser DateStartDate;
    private javax.swing.JLabel EndDate_Field;
    private javax.swing.JTextField GenerateReport_Field;
    private javax.swing.JLabel SelectReport_Label;
    private javax.swing.JLabel StartDate_Field;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnHomePage;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JComboBox<String> coboxSelectReport;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
