/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Package;

import Database_Package.DBConnectivity;
import Process_Package.Task;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usaamah, Felice Gregorio
 * @version     (10/04/2018) version 2.2
 * @since       (26/03/2018) version 1
 */
public class InspectTasks extends javax.swing.JFrame {
   /** The Jobs Code */
    private final String jobCode;
    /** The Employees Jobs Role */
    private final String jobRole;
    /** The Employees ID */
    private final String empID;
     /** The Tasks */
    private Task task;
    /**
     * Creates new form InspectTasks.
     * 
     * @param jobRole
     * @param jobCode
     * @param empID
     */
    public InspectTasks(String jobRole, String jobCode, String empID) {
        this.empID = empID;
        this.jobRole = jobRole;
        this.jobCode = jobCode;
        initComponents();
        sort();
        JobCode_lbl.setText("Job Code: " + jobCode);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        updatePriority_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        start_btn = new javax.swing.JButton();
        completed_btn = new javax.swing.JButton();
        late_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tasks_tbl = new javax.swing.JTable();
        Search_lbl = new javax.swing.JLabel();
        Search_txt = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        Location_lbl = new javax.swing.JLabel();
        Location_cmbo = new javax.swing.JComboBox<>();
        Status_lbl = new javax.swing.JLabel();
        Status_cmbo = new javax.swing.JComboBox<>();
        JobCode_lbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LogOut_btn = new javax.swing.JButton();
        HomePage_btn = new javax.swing.JButton();
        InspectTasks_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("inspecTasks"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        updatePriority_btn.setBackground(new java.awt.Color(0, 153, 255));
        updatePriority_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        updatePriority_btn.setForeground(new java.awt.Color(255, 255, 255));
        updatePriority_btn.setText("Update Priority");
        updatePriority_btn.setBorder(null);
        updatePriority_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePriority_btnActionPerformed(evt);
            }
        });

        Back_btn.setBackground(new java.awt.Color(0, 153, 255));
        Back_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Back_btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn.setText("Back");
        Back_btn.setBorder(null);
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        start_btn.setBackground(new java.awt.Color(0, 153, 255));
        start_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        start_btn.setForeground(new java.awt.Color(255, 255, 255));
        start_btn.setText("Start Task");
        start_btn.setBorder(null);
        start_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_btnActionPerformed(evt);
            }
        });

        completed_btn.setBackground(new java.awt.Color(0, 153, 255));
        completed_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        completed_btn.setForeground(new java.awt.Color(255, 255, 255));
        completed_btn.setText("Mark Completed");
        completed_btn.setBorder(null);
        completed_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completed_btnActionPerformed(evt);
            }
        });

        late_btn.setBackground(new java.awt.Color(0, 153, 255));
        late_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        late_btn.setForeground(new java.awt.Color(255, 255, 255));
        late_btn.setText("Mark Late");
        late_btn.setBorder(null);
        late_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                late_btnActionPerformed(evt);
            }
        });

        DBConnectivity myDB = new DBConnectivity();
        myDB.connect();
        ResultSet rs = myDB.read("SELECT task_ID AS 'Task ID', task_description AS 'Description', location AS 'Location', priority AS 'Priority', JobTasks.status AS 'Task Status', started AS 'Time Started', completed AS 'Time Completed', completion_shelf_slot AS 'Completion Shelf Slot' FROM Task INNER JOIN JobTasks USING (task_ID) WHERE job_code = '" + jobCode + "'");
        tasks_tbl.setModel(resultSetToTableModel(rs));
        myDB.closeConnection();
        tasks_tbl.setName("tasks_tbl"); // NOI18N
        tasks_tbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tasks_tbl);

        Search_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Search_lbl.setText("Search:");

        Search_txt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        search_btn.setBackground(new java.awt.Color(0, 153, 255));
        search_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("Search");
        search_btn.setBorder(null);
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        Location_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Location_lbl.setText("Location:");

        Location_cmbo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Location_cmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Copy Room", "Dark Room", "Development Area", "Printing Room", "Finishing Room", "Packing Department" }));
        Location_cmbo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Location_cmboItemStateChanged(evt);
            }
        });
        Location_cmbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Location_cmboActionPerformed(evt);
            }
        });

        Status_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Status_lbl.setText("Status:");

        Status_cmbo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Status_cmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Completed", "Ongoing" }));
        Status_cmbo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Status_cmboItemStateChanged(evt);
            }
        });
        Status_cmbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Status_cmboActionPerformed(evt);
            }
        });

        JobCode_lbl.setBackground(new java.awt.Color(0, 153, 255));
        JobCode_lbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JobCode_lbl.setForeground(new java.awt.Color(255, 255, 255));
        JobCode_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JobCode_lbl.setText("Job Code:  ");
        JobCode_lbl.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        LogOut_btn.setBackground(new java.awt.Color(255, 255, 255));
        LogOut_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        LogOut_btn.setForeground(new java.awt.Color(0, 153, 255));
        LogOut_btn.setText("Logout");
        LogOut_btn.setBorder(null);
        LogOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_btnActionPerformed(evt);
            }
        });

        HomePage_btn.setBackground(new java.awt.Color(255, 255, 255));
        HomePage_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        HomePage_btn.setForeground(new java.awt.Color(0, 153, 255));
        HomePage_btn.setText("Home Page");
        HomePage_btn.setBorder(null);
        HomePage_btn.setMaximumSize(new java.awt.Dimension(65, 19));
        HomePage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePage_btnActionPerformed(evt);
            }
        });

        InspectTasks_lbl.setBackground(new java.awt.Color(0, 153, 255));
        InspectTasks_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        InspectTasks_lbl.setForeground(new java.awt.Color(255, 255, 255));
        InspectTasks_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InspectTasks_lbl.setText("Inspect Tasks");
        InspectTasks_lbl.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LogOut_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HomePage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(InspectTasks_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomePage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InspectTasks_lbl)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(updatePriority_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(completed_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(late_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Search_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Location_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Location_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Status_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Status_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(JobCode_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JobCode_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Status_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Status_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Location_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Location_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(late_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(completed_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePriority_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Location_cmboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Location_cmboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Location_cmboActionPerformed
     /**
     * Logout Button
     * <p>
     * Closes the form and takes you back to the login form.
     */
    private void LogOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_btnActionPerformed
        this.dispose();
        Login_Form login = new Login_Form();
        login.setVisible(true);
    }//GEN-LAST:event_LogOut_btnActionPerformed
    /**
     * Search Button
     * <p>
     * Searches through the table.
     */
    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        String s = Search_txt.getText();
        filter(s);
    }//GEN-LAST:event_search_btnActionPerformed
     /**
     * Back Button
     * <p>
     * Closes the form taking you back to the previous form.
     */
    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        this.dispose();
        Inspect_Jobs ij = new Inspect_Jobs(jobRole, empID);
        ij.setVisible(true);
    }//GEN-LAST:event_Back_btnActionPerformed
     /**
     * Late Button
     * <p>
     * sets the selected task to late.
     */
    private void late_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_late_btnActionPerformed
        int row = tasks_tbl.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(null, "Please select a Task!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            Object taskID = tasks_tbl.getValueAt(row, 0);
            task = new Task(Integer.parseInt(taskID.toString()));
            task.taskLate(jobCode);
            tasks_tbl.setValueAt("Late", row, 4);
        }
    }//GEN-LAST:event_late_btnActionPerformed

    private void Status_cmboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Status_cmboActionPerformed
        
    }//GEN-LAST:event_Status_cmboActionPerformed
     /**
     * Status state changed
     * <p>
     * Filters the list with the selected Status.
     */
    private void Status_cmboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Status_cmboItemStateChanged
        String s = Status_cmbo.getSelectedItem().toString();
        filter(s);
    }//GEN-LAST:event_Status_cmboItemStateChanged
     /**
     * Location state changed
     * <p>
     * Filters the list with the selected location.
     */
    private void Location_cmboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Location_cmboItemStateChanged
        String s = Location_cmbo.getSelectedItem().toString();
        filter(s);
    }//GEN-LAST:event_Location_cmboItemStateChanged
     /**
     * HomePage Button
     * <p>
     * Closes the form and takes you back to the home page form.
     */
    private void HomePage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePage_btnActionPerformed
        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_HomePage_btnActionPerformed
     /**
     * Update priority Button
     * <p>
     * Changes the selected Tasks priority.
     */
    private void updatePriority_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePriority_btnActionPerformed
        int row = tasks_tbl.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(null, "Please select a Task!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            UpdatePriority up = new UpdatePriority(this, jobCode, Integer.parseInt(tasks_tbl.getValueAt(row, 0).toString()));
            up.setVisible(true);
        }
    }//GEN-LAST:event_updatePriority_btnActionPerformed
     /**
     * Start Task Button
     * <p>
     * Sets the selected task to start.
     */
    private void start_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_btnActionPerformed
        int row = tasks_tbl.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(null, "Please select a Task!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            if (tasks_tbl.getValueAt(row, 5) == null){
                if (tasks_tbl.getValueAt(row, 6) == null){
                   Object taskID = tasks_tbl.getValueAt(row, 0);
                   task = new Task(Integer.parseInt(taskID.toString()));
                   task.startTask(jobCode, empID);
                   tasks_tbl.setValueAt("Active", row, 4);
                   tasks_tbl.setValueAt(new Timestamp(System.currentTimeMillis()), row, 5);
                } else {
                    JOptionPane.showMessageDialog(null, "Cannot start an already completed task!", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Cannot start an already started task!", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_start_btnActionPerformed
     /**
     * Completed Button
     * <p>
     * Sets the selected task to Completed.
     */
    private void completed_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completed_btnActionPerformed
        int row = tasks_tbl.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(null, "Please select a Task!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            if (tasks_tbl.getValueAt(row, 6) == null){
                if (tasks_tbl.getValueAt(row, 5) == null){
                    JOptionPane.showMessageDialog(null, "This task has not been started!", "Error!", JOptionPane.ERROR_MESSAGE);
                } else {
                    Object taskID = tasks_tbl.getValueAt(row, 0);
                    String shelfSlot = JOptionPane.showInputDialog(null, "Please enter shelf slot on completion:", "Shelf Slot Required", JOptionPane.QUESTION_MESSAGE);
                    task = new Task(Integer.parseInt(taskID.toString()));
                    task.taskCompleted(jobCode);
                    task.setCompletionShelfSlot(shelfSlot, jobCode);
                    tasks_tbl.setValueAt("Completed", row, 4);
                    tasks_tbl.setValueAt(new Timestamp(System.currentTimeMillis()), row, 6);
                    tasks_tbl.setValueAt(shelfSlot, row, 7);
                } 
            } else {
                JOptionPane.showMessageDialog(null, "Cannot complete an already completed task!", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_completed_btnActionPerformed
     /**
     * Sort Table
     * <p>
     * Sorts through the table with the Tasks data.
     */
    public void sort(){
        DefaultTableModel dm = (DefaultTableModel) tasks_tbl.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dm);
        tasks_tbl.setRowSorter(trs);
    }
    /**
     * Filter Table
     * <p>
     * Filters through the list with the Tasks data.
     */
    public void filter(String s){
        DefaultTableModel dm = (DefaultTableModel) tasks_tbl.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dm);
        tasks_tbl.setRowSorter(trs);
        
        if (!"None".equals(s) || s.isEmpty()){
            trs.setRowFilter(RowFilter.regexFilter(s));
        } else {
            tasks_tbl.setRowSorter(trs);
        }
    }
     
    /**
     * Table
     * <p>
     * Creates a table 
     * @return populated table with the Task data.
     */
    public static DefaultTableModel resultSetToTableModel(ResultSet rs) {
        ResultSetMetaData md;
        
        Vector<String> columnNames = new Vector<>();
        Vector<Vector<Object>> data = new Vector<>();
        
        try {
            md = rs.getMetaData();
            
            // names of columns
            int columnCount = md.getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
                columnNames.add(md.getColumnLabel(i));
            }

            // data of the table
            while (rs.next()) {
                Vector<Object> vector = new Vector<>();
                for (int i = 1; i <= columnCount; i++) {
                    vector.add(rs.getObject(i));
                }
                data.add(vector);
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(InspectTasks.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return new DefaultTableModel(data, columnNames);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InspectTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InspectTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InspectTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InspectTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InspectTasks("Office Manager", "ABN54", "FG12").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JButton HomePage_btn;
    private javax.swing.JLabel InspectTasks_lbl;
    private javax.swing.JLabel JobCode_lbl;
    private javax.swing.JComboBox<String> Location_cmbo;
    private javax.swing.JLabel Location_lbl;
    private javax.swing.JButton LogOut_btn;
    private javax.swing.JLabel Search_lbl;
    private javax.swing.JTextField Search_txt;
    private javax.swing.JComboBox<String> Status_cmbo;
    private javax.swing.JLabel Status_lbl;
    private javax.swing.JButton completed_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton late_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JButton start_btn;
    public javax.swing.JTable tasks_tbl;
    private javax.swing.JButton updatePriority_btn;
    // End of variables declaration//GEN-END:variables
}
