/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Package;

import Database_Package.DBConnectivity;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author umahm, Kimberly Eslami
 * @version (06/04/18) version 2
 * @since (29/03/18) version 1
 */
public class Login_Form extends javax.swing.JFrame {

    /**
     * connection to the Database
     */
    private final DBConnectivity myDB = new DBConnectivity();
    /**
     * the employees job role
     */
    private String jobRole;
    /** The Employees ID. */
    private String empID;

    /**
     * Creates new form Login_Form2
     */
    public Login_Form() {
        this.setResizable(false);
        initComponents();
        
        Toolkit tool = Toolkit.getDefaultToolkit();
        
        int height = (int) tool.getScreenSize().getHeight();
        int width = (int) tool.getScreenSize().getWidth();
        this.setSize(width, height);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SignIn_lbl = new javax.swing.JLabel();
        EmployeeID_lbl = new javax.swing.JLabel();
        EmployeeID_txt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Password_lbl = new javax.swing.JLabel();
        Password_txt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        Login_Btn = new javax.swing.JButton();
        SignUP_lbl = new javax.swing.JLabel();
        Signup_btn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Restore_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ForgottenPassword_btn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        SignIn_lbl.setBackground(new java.awt.Color(0, 153, 255));
        SignIn_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SignIn_lbl.setForeground(new java.awt.Color(255, 255, 255));
        SignIn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignIn_lbl.setText("Sign In");
        SignIn_lbl.setOpaque(true);

        EmployeeID_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        EmployeeID_lbl.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeID_lbl.setText("Employee ID:");

        EmployeeID_txt.setBackground(new java.awt.Color(0, 153, 255));
        EmployeeID_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        EmployeeID_txt.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeID_txt.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        Password_lbl.setBackground(new java.awt.Color(0, 153, 255));
        Password_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Password_lbl.setForeground(new java.awt.Color(255, 255, 255));
        Password_lbl.setText("Password:");

        Password_txt.setBackground(new java.awt.Color(0, 153, 255));
        Password_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Password_txt.setForeground(new java.awt.Color(255, 255, 255));
        Password_txt.setBorder(null);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        Login_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Login_Btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Login_Btn.setForeground(new java.awt.Color(0, 153, 255));
        Login_Btn.setText("Login");
        Login_Btn.setBorder(null);
        Login_Btn.setBorderPainted(false);
        Login_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_BtnActionPerformed(evt);
            }
        });

        SignUP_lbl.setBackground(new java.awt.Color(0, 153, 255));
        SignUP_lbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SignUP_lbl.setForeground(new java.awt.Color(255, 255, 255));
        SignUP_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUP_lbl.setText("Don't have an account?");
        SignUP_lbl.setOpaque(true);

        Signup_btn.setBackground(new java.awt.Color(255, 255, 255));
        Signup_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Signup_btn.setForeground(new java.awt.Color(0, 153, 255));
        Signup_btn.setText("Sign Up");
        Signup_btn.setBorder(null);
        Signup_btn.setBorderPainted(false);
        Signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signup_btnActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EmployeeID_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(293, 293, 293))
                            .addComponent(EmployeeID_txt))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Password_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(303, 303, 303))
                            .addComponent(Password_txt))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(SignIn_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(169, 169, 169))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Login_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(SignUP_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Signup_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(90, 90, 90)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignIn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(EmployeeID_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(Password_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Login_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(SignUP_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Restore_btn.setBackground(new java.awt.Color(0, 153, 255));
        Restore_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Restore_btn.setForeground(new java.awt.Color(255, 255, 255));
        Restore_btn.setText("Restore");
        Restore_btn.setBorder(null);
        Restore_btn.setBorderPainted(false);
        Restore_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restore_btnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Forgotten Your Password?");

        ForgottenPassword_btn.setBackground(new java.awt.Color(0, 153, 255));
        ForgottenPassword_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        ForgottenPassword_btn.setForeground(new java.awt.Color(255, 255, 255));
        ForgottenPassword_btn.setText("Forgot Password");
        ForgottenPassword_btn.setBorder(null);
        ForgottenPassword_btn.setBorderPainted(false);
        ForgottenPassword_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgottenPassword_btnActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 153, 255));
        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Would You Like To Restore The Database?");

        jSeparator5.setBackground(new java.awt.Color(0, 153, 255));
        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator5))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Restore_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ForgottenPassword_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(ForgottenPassword_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addComponent(Restore_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_BtnActionPerformed
        /**
         * allows user to login to the system
         */
        
        myDB.connect();
        Connection con = myDB.getConn();
        try {
            con.setAutoCommit(false);
            String name = EmployeeID_txt.getText();
            
            String password = new String(Password_txt.getPassword());
            ResultSet rs = myDB.read("select employee_ID, job_role, password from employee where employee_ID='" + name + "' and password='" + password + "'");

        
            if (rs.next()) {
                this.dispose();
                jobRole = rs.getString("job_role");
                empID = rs.getString("employee_ID");
                HomePage hp = new HomePage(jobRole, empID);
                hp.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Username or Password is Incorrect");
            }
            con.commit();
        } catch (SQLException ex) {
            if (con != null) {
            try {
                System.err.print("Transaction rolling back!");
                con.rollback();
            } catch (SQLException ex1) {
                Logger.getLogger(DBConnectivity.class.getName()).log(Level.SEVERE, null, ex1);
            }
	}
        }finally{
            try {
                con.setAutoCommit(true);
            } catch (SQLException ex) {
                Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
            myDB.closeConnection();
        }
    }//GEN-LAST:event_Login_BtnActionPerformed

    private void ForgottenPassword_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgottenPassword_btnActionPerformed
        /**
         * takes you to the verification page
         */
        Verification v = new Verification();
        v.setVisible(true);
    }//GEN-LAST:event_ForgottenPassword_btnActionPerformed

    private void Signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_btnActionPerformed
        /**
         * takes you to the new employee account form
         */
        try {
            this.dispose();
            EmployeeAccount emp = new EmployeeAccount();
            emp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Signup_btnActionPerformed

    private void Restore_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restore_btnActionPerformed
        if (EmployeeID_txt.getText().equals("0000") && new String(Password_txt.getPassword()).equals("admin123")){
            this.dispose();
            BackupAndRestore br = new BackupAndRestore("Admin", empID);
            br.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Administation credentials incorrect! Please try again!");
        }
    }//GEN-LAST:event_Restore_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Form().setExtendedState(JFrame.MAXIMIZED_BOTH);
                new Login_Form().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeID_lbl;
    private javax.swing.JTextField EmployeeID_txt;
    private javax.swing.JButton ForgottenPassword_btn;
    private javax.swing.JButton Login_Btn;
    private javax.swing.JLabel Password_lbl;
    private javax.swing.JPasswordField Password_txt;
    private javax.swing.JButton Restore_btn;
    private javax.swing.JLabel SignIn_lbl;
    private javax.swing.JLabel SignUP_lbl;
    private javax.swing.JButton Signup_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
