/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Package;

import Reports_Package.SummaryPerformanceReport;
import java.awt.print.PrinterException;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author umahm, Felice Gregorio
 * 
 * @version     (11/04/2018) version 2.1
 * @since       (26/03/2018) version 1
 */
public class SummaryPerformanceReportForm extends javax.swing.JFrame {
    /** New JFrame */
    private final JFrame frame;
     /** The Start Date */
    private final Date start;
       /**The End Date */
    private final Date end;
    /** The Employee Job role*/
    private final String jobRole;
     /** Sets the date format */
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    /**The Summary performance report */
    private final SummaryPerformanceReport spr;
      /** Array list with the Reports */
    private final ArrayList<ResultSet> reports;
    /** The Employees ID. */
    private final String empID;
    
    /**
     * Creates new form SummaryPerformanceReport.
     * 
     * @param frame new JFrame
     * @param jobRole  Employee's job role
     * @param start  start date 
     * @param end  end date 
     * @param empID The employee ID
     */
    public SummaryPerformanceReportForm(JFrame frame, String jobRole, Date start, Date end, String empID) {
        this.empID = empID;
        this.frame = frame; 
        this.jobRole = jobRole;
        this.start = start;
        this.end = end;
        
        spr = new SummaryPerformanceReport(start, end);
        
        if (frame.getName().equals("viewReports")){
            reports = spr.generate(false);
        } else {
            reports = spr.generate(true);
        }
        
        initComponents();
        period_lbl.setText("Period: " + sdf.format(start) + " - " + sdf.format(end));
        forPeriod_lbl.setText("For Period: " + sdf.format(start) + " - " + sdf.format(end));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back_btn = new javax.swing.JButton();
        Print_btn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        forPeriod_tbl = new javax.swing.JTable();
        forPeriod_lbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        nShift1_tbl = new javax.swing.JTable();
        Nightshift_lbl = new javax.swing.JLabel();
        Dayshift2_lbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dShift2_tbl = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        dShift1_tbl = new javax.swing.JTable();
        Dayshift1_lbl = new javax.swing.JLabel();
        period_lbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LogOut_btn = new javax.swing.JButton();
        HomePage_btn = new javax.swing.JButton();
        ScheduleReport_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Back_btn.setBackground(new java.awt.Color(0, 153, 255));
        Back_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Back_btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn.setText("Back");
        Back_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back_btn.setContentAreaFilled(false);
        Back_btn.setOpaque(true);
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        Print_btn.setBackground(new java.awt.Color(0, 153, 255));
        Print_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Print_btn.setForeground(new java.awt.Color(255, 255, 255));
        Print_btn.setText("Print ");
        Print_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Print_btn.setContentAreaFilled(false);
        Print_btn.setOpaque(true);
        Print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_btnActionPerformed(evt);
            }
        });

        forPeriod_tbl.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        forPeriod_tbl.setModel(setForPeriodTable());
        forPeriod_tbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(forPeriod_tbl);

        forPeriod_lbl.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        forPeriod_lbl.setText("For Period: DD/MM/YYYY - DD/MM/YYYY");

        nShift1_tbl.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        nShift1_tbl.setModel(setNShift1Table());
        nShift1_tbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(nShift1_tbl);

        Nightshift_lbl.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Nightshift_lbl.setText("Night Shift 1: 10pm to 5am");

        Dayshift2_lbl.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Dayshift2_lbl.setText("Day Shift 2: 2:30pm to 10pm");

        dShift2_tbl.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        dShift2_tbl.setModel(setDShift2Table());
        dShift2_tbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(dShift2_tbl);

        dShift1_tbl.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        dShift1_tbl.setModel(setDShift1Table());
        dShift1_tbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(dShift1_tbl);

        Dayshift1_lbl.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Dayshift1_lbl.setText("Day Shift 1: 5am to 2pm");

        period_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        period_lbl.setText("Period: DD/MM/YY - DD/MM/YY");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        LogOut_btn.setBackground(new java.awt.Color(255, 255, 255));
        LogOut_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        LogOut_btn.setForeground(new java.awt.Color(0, 153, 255));
        LogOut_btn.setText("Logout");
        LogOut_btn.setBorder(null);
        LogOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_btnActionPerformed(evt);
            }
        });

        HomePage_btn.setBackground(new java.awt.Color(255, 255, 255));
        HomePage_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        HomePage_btn.setForeground(new java.awt.Color(0, 153, 255));
        HomePage_btn.setText("Home Page");
        HomePage_btn.setBorder(null);
        HomePage_btn.setMaximumSize(new java.awt.Dimension(65, 19));
        HomePage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePage_btnActionPerformed(evt);
            }
        });

        ScheduleReport_lbl.setBackground(new java.awt.Color(0, 153, 255));
        ScheduleReport_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        ScheduleReport_lbl.setForeground(new java.awt.Color(255, 255, 255));
        ScheduleReport_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScheduleReport_lbl.setText("Summary Performance Report");
        ScheduleReport_lbl.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScheduleReport_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(HomePage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogOut_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomePage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScheduleReport_lbl)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 437, Short.MAX_VALUE)
                .addComponent(Print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(forPeriod_lbl))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(Dayshift1_lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(period_lbl))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(Dayshift2_lbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(Nightshift_lbl))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(period_lbl)
                .addGap(14, 14, 14)
                .addComponent(Dayshift1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Dayshift2_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Nightshift_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(forPeriod_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     /**
     * Logout Button
     * <p>
     * Closes the form and takes you back to the login form.
     */
    private void LogOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_btnActionPerformed
        this.dispose();
        Login_Form login = new Login_Form();
        login.setVisible(true);
    }//GEN-LAST:event_LogOut_btnActionPerformed
     /**
     * Back Button
     * <p>
     * Closes the form taking you back to the previous form.
     */
    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_Back_btnActionPerformed
     /**
     * Print Button
     * <p>
     * Prints the Report.
     */
    private void Print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_btnActionPerformed
        MessageFormat header = new MessageFormat(spr.getReptName() + "\n" + period_lbl.getText());
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");
        
        try {
            dShift1_tbl.print(JTable.PrintMode.NORMAL, header, footer);
            dShift2_tbl.print(JTable.PrintMode.NORMAL, header, footer);
            nShift1_tbl.print(JTable.PrintMode.NORMAL, header, footer);
            forPeriod_tbl.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(SummaryPerformanceReportForm.class.getName()).log(Level.SEVERE, null, ex);
            System.err.format("Cannot print Report!", ex.getMessage());
        }
    }//GEN-LAST:event_Print_btnActionPerformed
    /**
     * HomePage Button
     * <p>
     * Closes the form and takes you back to the home page form.
     */
    private void HomePage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePage_btnActionPerformed
        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_HomePage_btnActionPerformed
    /** Set Day shift 1 table.
     *  <p>
     * Sets the values in the day shift 1 table.
     * @return returns the reports for day shift 1.
     */
    public TableModel setDShift1Table(){
        return ResultSetToTableModel(reports.get(0));
    }
     /** Set Day shift 2 table.
     *  <p>
     * Sets the values in the day shift 2 table.
     * @return returns the reports for day shift 2.
     */
    public TableModel setDShift2Table(){
        return ResultSetToTableModel(reports.get(1));
    }
     /** Set Night shift 1 table.
     *  <p>
     * Sets the values in the night shift 1 table.
     * @return returns the reports for night shift 1.
     */
    public TableModel setNShift1Table(){
        return ResultSetToTableModel(reports.get(2));
    }
      /** Set for period table.
     *  <p>
     * Sets the values in the for a period of time specified
     * @return returns the reports for the period of time specified
     */
    public TableModel setForPeriodTable(){
        return ResultSetToTableModel(reports.get(3));
    }
     /**
     * Table
     * <p>
     * Creates new table and populates it with data from the DB
     * @param rs Result set
     * @return  table populated with the reports data.
     */
    public static DefaultTableModel ResultSetToTableModel(ResultSet rs) {
        ResultSetMetaData md;
        
        Vector<String> columnNames = new Vector<>();
        Vector<Vector<Object>> data = new Vector<>();
        
        try {
            md = rs.getMetaData();
            
            // names of columns
            int columnCount = md.getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
                columnNames.add(md.getColumnLabel(i));
            }

            // data of the table
            while (rs.next()) {
                Vector<Object> vector = new Vector<>();
                for (int i = 1; i <= columnCount; i++) {
                    vector.add(rs.getObject(i));
                }
                data.add(vector);
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(InspectTasks.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return new DefaultTableModel(data, columnNames);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SummaryPerformanceReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SummaryPerformanceReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SummaryPerformanceReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SummaryPerformanceReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SummaryPerformanceReportForm(new Generate_Report("Office Manager", "FG12"), "Office Manager", new Date(new GregorianCalendar(2018, 01, 24).getTimeInMillis()), new Date(new GregorianCalendar(2018, 01, 24).getTimeInMillis()), "FG12").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JLabel Dayshift1_lbl;
    private javax.swing.JLabel Dayshift2_lbl;
    private javax.swing.JButton HomePage_btn;
    private javax.swing.JButton LogOut_btn;
    private javax.swing.JLabel Nightshift_lbl;
    private javax.swing.JButton Print_btn;
    private javax.swing.JLabel ScheduleReport_lbl;
    private javax.swing.JTable dShift1_tbl;
    private javax.swing.JTable dShift2_tbl;
    private javax.swing.JLabel forPeriod_lbl;
    private javax.swing.JTable forPeriod_tbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable nShift1_tbl;
    private javax.swing.JLabel period_lbl;
    // End of variables declaration//GEN-END:variables
}
