/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Package;

import Database_Package.DBConnectivity;
import Process_Package.Task;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usaamah, Felice Gregorio
 * @version     (10/04/2018) version 3
 * @since       (26/03/2018) version 1
 */
public class Tasks extends javax.swing.JFrame {
    /** The Employees Job role. */
    private final String jobRole;
    /** The Employees ID. */
    private final String empID;
    /**
     * Creates new form Tasks
     * @param jobRole employee's job role
     * @param empID The employee ID.
     */
    public Tasks(String jobRole, String empID) {
        this.empID = empID;
        this.jobRole = jobRole;
        initComponents();
        Toolkit tool = Toolkit.getDefaultToolkit();
        int height = (int) tool.getScreenSize().getHeight();
        int width = (int) tool.getScreenSize().getWidth();
        this.setSize(width, height);
        sort();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back_btn = new javax.swing.JButton();
        RemoveTask_btn = new javax.swing.JButton();
        CreateTasks_btn = new javax.swing.JButton();
        Update_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tasks_tbl = new javax.swing.JTable();
        Search_lbl = new javax.swing.JLabel();
        Search_txt = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        Location_cmbo = new javax.swing.JComboBox<>();
        Location_lbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Tasks_lbl = new javax.swing.JLabel();
        LogOut_btn = new javax.swing.JButton();
        HomePage_btn = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Back_btn.setBackground(new java.awt.Color(0, 153, 255));
        Back_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Back_btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn.setText("Back");
        Back_btn.setBorder(null);
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        RemoveTask_btn.setBackground(new java.awt.Color(0, 153, 255));
        RemoveTask_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        RemoveTask_btn.setForeground(new java.awt.Color(255, 255, 255));
        RemoveTask_btn.setText("Remove Task");
        RemoveTask_btn.setBorder(null);
        RemoveTask_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveTask_btnActionPerformed(evt);
            }
        });

        CreateTasks_btn.setBackground(new java.awt.Color(0, 153, 255));
        CreateTasks_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        CreateTasks_btn.setForeground(new java.awt.Color(255, 255, 255));
        CreateTasks_btn.setText("Create Task");
        CreateTasks_btn.setBorder(null);
        CreateTasks_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateTasks_btnActionPerformed(evt);
            }
        });

        Update_btn.setBackground(new java.awt.Color(0, 153, 255));
        Update_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Update_btn.setForeground(new java.awt.Color(255, 255, 255));
        Update_btn.setText("Update ");
        Update_btn.setBorder(null);
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        DBConnectivity myDB = new DBConnectivity();
        myDB.connect();
        ResultSet rs = myDB.read("SELECT task_ID AS 'Task ID', task_description AS 'Description', location AS 'Location', price AS 'Price', duration AS 'Duration', shelf_slot AS 'Shelf Slot', deleted AS 'Is Deleted' FROM Task");
        tasks_tbl.setModel(resultSetToTableModel(rs));
        tasks_tbl.getTableHeader().setReorderingAllowed(false);
        myDB.closeConnection();
        jScrollPane1.setViewportView(tasks_tbl);

        Search_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Search_lbl.setText("Search:");

        Search_txt.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        search_btn.setBackground(new java.awt.Color(0, 153, 255));
        search_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("Search");
        search_btn.setBorder(null);
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        Location_cmbo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Location_cmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Copy Room", "Dark Room", "Development Area", "Printing Room", "Finishing Room", "Packing Department" }));
        Location_cmbo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Location_cmboItemStateChanged(evt);
            }
        });
        Location_cmbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Location_cmboActionPerformed(evt);
            }
        });

        Location_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Location_lbl.setText("Location:");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        Tasks_lbl.setBackground(new java.awt.Color(0, 153, 255));
        Tasks_lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Tasks_lbl.setForeground(new java.awt.Color(255, 255, 255));
        Tasks_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tasks_lbl.setText("Tasks");
        Tasks_lbl.setOpaque(true);

        LogOut_btn.setBackground(new java.awt.Color(255, 255, 255));
        LogOut_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        LogOut_btn.setForeground(new java.awt.Color(0, 153, 255));
        LogOut_btn.setText("Logout");
        LogOut_btn.setBorder(null);
        LogOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_btnActionPerformed(evt);
            }
        });

        HomePage_btn.setBackground(new java.awt.Color(255, 255, 255));
        HomePage_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        HomePage_btn.setForeground(new java.awt.Color(0, 153, 255));
        HomePage_btn.setText("Home Page");
        HomePage_btn.setBorder(null);
        HomePage_btn.setMaximumSize(new java.awt.Dimension(65, 19));
        HomePage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePage_btnActionPerformed(evt);
            }
        });

        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\kimbe\\Documents\\Uni Work\\Second Year Uni\\Team project\\WhatsApp Image 2018-04-18 at 2.43.23 PM.jpeg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogOut_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HomePage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(Tasks_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomePage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(Tasks_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Search_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(Location_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Location_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addGap(248, 248, 248)
                        .addComponent(RemoveTask_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(342, 342, 342)
                        .addComponent(CreateTasks_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(260, 260, 260)
                        .addComponent(Update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_btn)
                    .addComponent(Location_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Location_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveTask_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateTasks_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /** Create tasks button
    * <p>
    * opens the create tasks form
    * Adds the new task to the table.
    */
    private void CreateTasks_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateTasks_btnActionPerformed
        this.dispose();
        CreateTasks ct = new CreateTasks(jobRole, empID);
        ct.setVisible(true);
    }//GEN-LAST:event_CreateTasks_btnActionPerformed
    /** Remove tasks button
    * <p>
    * Removes selected task from the database and Removes it from the table. 
    */
    private void RemoveTask_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveTask_btnActionPerformed
        int row = tasks_tbl.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(null, "Please select a Task!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            Object taskID = tasks_tbl.getValueAt(row, 0);
            int option = JOptionPane.showConfirmDialog(null, "Are you sure you wish to delete this task?", "Warning!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (option == JOptionPane.YES_OPTION){
                Task task = new Task(Integer.parseInt(taskID.toString()));
                task.delete();
                if (task.isDeleted()){
                    tasks_tbl.setValueAt(1, row, 6);
                } else {
                    DefaultTableModel dtm = (DefaultTableModel) tasks_tbl.getModel();
                    dtm.removeRow(row);
                }
            }
        }
    }//GEN-LAST:event_RemoveTask_btnActionPerformed

    private void Location_cmboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Location_cmboActionPerformed
        
    }//GEN-LAST:event_Location_cmboActionPerformed
    /** Search button
    * <p>
    * Searches for a task in the table. 
    */
    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        String s = Search_txt.getText();
        filter(s);
    }//GEN-LAST:event_search_btnActionPerformed
    /**
     * Back Button
     * <p>
     * Closes the form taking you back to the previous form.
     */
    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_Back_btnActionPerformed
     /** Update tasks button
     * <p>
     * Opens the update tasks form for the selected task. 
     */
    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
        int row = tasks_tbl.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(null, "Please select a Task!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            Object taskID = tasks_tbl.getValueAt(row, 0);
            this.dispose();
            UpdateTask ut = new UpdateTask(jobRole, Integer.parseInt(taskID.toString()), empID);
            ut.setVisible(true);
        }
    }//GEN-LAST:event_Update_btnActionPerformed
    /**
     * Logout Button
     * <p>
     * Closes the form and takes you back to the login form.
     */
    private void LogOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_btnActionPerformed
        this.dispose();
        Login_Form login = new Login_Form();
        login.setVisible(true);
    }//GEN-LAST:event_LogOut_btnActionPerformed
     /**
     * Location state changed
     * <p>
     * Filters the list with the selected location.
     */
    private void Location_cmboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Location_cmboItemStateChanged
        String s = Location_cmbo.getSelectedItem().toString();
        filter(s);
    }//GEN-LAST:event_Location_cmboItemStateChanged
    /**
     * HomePage Button
     * <p>
     * Closes the form and takes you back to the home page form.
     */
    private void HomePage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePage_btnActionPerformed
        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_HomePage_btnActionPerformed
     /**
     * Sort List
     * <p>
     * Sorts through the table with the Tasks data.
     */
    public void sort(){
        DefaultTableModel dm = (DefaultTableModel) tasks_tbl.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dm);
        tasks_tbl.setRowSorter(trs);
    }
     /**
     * Filter List
     * <p>
     * Filters through the list with the Tasks data.
     * @param s The string to 
     */
    public void filter(String s){
        DefaultTableModel dm = (DefaultTableModel) tasks_tbl.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(dm);
        tasks_tbl.setRowSorter(trs);
        
        if (!"None".equals(s) || s.isEmpty()){
            trs.setRowFilter(RowFilter.regexFilter(s));
        } else {
            tasks_tbl.setRowSorter(trs);
        }
    }
      /**
     * Table
     * <p>
     * Creates new table and populates it with data from the DB.
     * @param rs
     * @return table populated with the report data.
     */
    public static DefaultTableModel resultSetToTableModel(ResultSet rs) {
        ResultSetMetaData md;
        
        Vector<String> columnNames = new Vector<>();
        Vector<Vector<Object>> data = new Vector<>();
        
        try {
            md = rs.getMetaData();
            
            // names of columns
            int columnCount = md.getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
                columnNames.add(md.getColumnLabel(i));
            }

            // data of the table
            while (rs.next()) {
                Vector<Object> vector = new Vector<>();
                for (int i = 1; i <= columnCount; i++) {
                    vector.add(rs.getObject(i));
                }
                data.add(vector);
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(InspectTasks.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return new DefaultTableModel(data, columnNames);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tasks("Office Manager", "FG12").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JButton CreateTasks_btn;
    private javax.swing.JButton HomePage_btn;
    private javax.swing.JComboBox<String> Location_cmbo;
    private javax.swing.JLabel Location_lbl;
    private javax.swing.JButton LogOut_btn;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton RemoveTask_btn;
    private javax.swing.JLabel Search_lbl;
    private javax.swing.JTextField Search_txt;
    private javax.swing.JLabel Tasks_lbl;
    private javax.swing.JButton Update_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search_btn;
    private javax.swing.JTable tasks_tbl;
    // End of variables declaration//GEN-END:variables
}
