/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Package;

import System_Package.Reader;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Allen, Felice Gregoiro
 * 
 * @version     (11/04/2018) version 2
 * @since       (26/03/2018) version 1
 */
public class View_Reports extends javax.swing.JFrame {
    /** The Employees Job role.  */
    private final String jobRole;
    /** Reads the Generates report file. */
    private final Reader reader = new Reader("generatedReports.txt");
    /** ArrayList for the reports. */
    private ArrayList<String> reports = new ArrayList<>();
    /** Sets the date format. */
    private final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    /** The Employees ID. */
    private final String empID;
    
    /**
     * Creates new form View_Reports.
     * @param jobRole employee's job role
     * @param empID employee ID
     */
    public View_Reports(String jobRole, String empID) {
        this.empID = empID;
        this.jobRole = jobRole;
        Toolkit tool = Toolkit.getDefaultToolkit();
        int height = (int) tool.getScreenSize().getHeight();
        int width = (int) tool.getScreenSize().getWidth();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newRept_btn = new javax.swing.JButton();
        view_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reports_lst = new javax.swing.JList<>();
        reports_lbl = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        type_cmbo = new javax.swing.JComboBox<>();
        date_dte = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        reset_btn = new javax.swing.JButton();
        filter_lbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        btnLogOut = new javax.swing.JButton();
        btnHomePage = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        Back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("viewReports"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        newRept_btn.setBackground(new java.awt.Color(0, 153, 255));
        newRept_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        newRept_btn.setForeground(new java.awt.Color(255, 255, 255));
        newRept_btn.setText("Create New Report");
        newRept_btn.setBorder(null);
        newRept_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRept_btnActionPerformed(evt);
            }
        });

        view_btn.setBackground(new java.awt.Color(0, 153, 255));
        view_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        view_btn.setForeground(new java.awt.Color(255, 255, 255));
        view_btn.setText("View");
        view_btn.setToolTipText("");
        view_btn.setBorder(null);
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });

        reports_lst.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        DefaultListModel lstModel = new DefaultListModel();

        reports = reader.readGeneratedReports();

        if (reports != null){
            for(String s : reports){
                try {
                    String[] report = s.split(",");
                    String dateTime = report[0];
                    String name = report[1];

                    java.util.Date strtDate = sdf.parse(report[2]);
                    java.sql.Date start = new java.sql.Date(strtDate.getTime());

                    java.util.Date endDate = sdf.parse(report[3]);
                    java.sql.Date end = new java.sql.Date(endDate.getTime());

                    String custID = report[4];

                    lstModel.addElement(dateTime + " - " + name + " - " + start + " - " + end + " - " + custID);

                } catch (ParseException ex) {
                    Logger.getLogger(View_Reports.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        reports_lst.setModel(lstModel);
        jScrollPane1.setViewportView(reports_lst);

        reports_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        reports_lbl.setText("Generated Reports:");
        reports_lbl.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel16.setText("Type of Report:");
        jLabel16.setToolTipText("");

        type_cmbo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        type_cmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Individual Report", "Individual Performance Report", "Summary Performance Report" }));
        type_cmbo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                type_cmboItemStateChanged(evt);
            }
        });

        date_dte.setDateFormatString("dd/MM/yy");
        date_dte.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_dtePropertyChange(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel15.setText("Date Created:");
        jLabel15.setToolTipText("");

        reset_btn.setBackground(new java.awt.Color(0, 153, 255));
        reset_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        reset_btn.setForeground(new java.awt.Color(255, 255, 255));
        reset_btn.setText("Reset");
        reset_btn.setBorder(null);
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });

        filter_lbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        filter_lbl.setText("Filter Reports:");
        filter_lbl.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jTextField5.setBackground(new java.awt.Color(0, 153, 255));
        jTextField5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("View Report");
        jTextField5.setToolTipText("");
        jTextField5.setBorder(null);

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(0, 153, 255));
        btnLogOut.setText("Logout");
        btnLogOut.setBorder(null);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnHomePage.setBackground(new java.awt.Color(255, 255, 255));
        btnHomePage.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnHomePage.setForeground(new java.awt.Color(0, 153, 255));
        btnHomePage.setText("Home Page");
        btnHomePage.setBorder(null);
        btnHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Logo))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Back_btn.setBackground(new java.awt.Color(0, 153, 255));
        Back_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Back_btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn.setText("Back");
        Back_btn.setToolTipText("");
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(reports_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1190, 1190, 1190))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(newRept_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(199, 199, 199)
                                .addComponent(view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(filter_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(type_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(225, 225, 225))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(date_dte, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81)
                                        .addComponent(reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(435, 435, 435))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(reports_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newRept_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(137, 137, 137))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(filter_lbl)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_dte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(type_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /** Type State changed
     * <p>
     * Filters the list with the selected type.
     */
    private void type_cmboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_type_cmboItemStateChanged
        String item = type_cmbo.getSelectedItem().toString();
        filterName(item);
    }//GEN-LAST:event_type_cmboItemStateChanged
    /** Date State changed
     * <p>
     * Filters the list with the date entered.
     */
    private void date_dtePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_dtePropertyChange
        String date = "";
        String format = date_dte.getDateFormatString();
        if(date_dte.getDate() != null){
            date = new SimpleDateFormat(format).format(date_dte.getDate());
        }
        filterDate(date);
    }//GEN-LAST:event_date_dtePropertyChange
   /** Reset button
     * <p>
     * Sets the values to empty.
     */
    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
       type_cmbo.setSelectedIndex(0);
       date_dte.setDate(null);
    }//GEN-LAST:event_reset_btnActionPerformed
     /** new report button
     * <p>
     * closes the form and opens the generate report form.
     */
    private void newRept_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRept_btnActionPerformed
        this.dispose();
        Generate_Report gr = new Generate_Report(jobRole, empID);
        gr.setVisible(true);
    }//GEN-LAST:event_newRept_btnActionPerformed
     /** view button
     * <p>
     * views the report.
     */
    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
        String[] selectedRept = reports_lst.getSelectedValue().split(" - ");
        String selectedReportDate = selectedRept[0];
        String selectedReport = selectedRept[1];

        for(String s : reports){
            try {
                String[] report = s.split(",");
                String dateTime = report[0];
                String name = report[1];
                
                java.util.Date strtDate = sdf.parse(report[2]);
                java.sql.Date start = new java.sql.Date(strtDate.getTime());
                
                java.util.Date endDate = sdf.parse(report[3]);
                java.sql.Date end = new java.sql.Date(endDate.getTime());
                
                String custID = report[4];
            
                if(name.matches(selectedReport) && dateTime.matches(selectedReportDate)){
                    switch (name){
                        case "Individual Report":
                            this.dispose();
                            IndividualReportForm ir = new IndividualReportForm(this, jobRole, custID, start, end, empID);
                            ir.setVisible(true);
                            break;
                        case "Individual Performance Report":
                            this.dispose();
                            IndividualPerformanceReportForm ipr = new IndividualPerformanceReportForm(this, jobRole, start, end, empID);
                            ipr.setVisible(true);
                            break;
                        case "Summary Performance Report":
                            this.dispose();
                            SummaryPerformanceReportForm spr = new SummaryPerformanceReportForm(this,jobRole, start, end, empID);
                            spr.setVisible(true);
                            break; 
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(View_Reports.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_view_btnActionPerformed
     /**
     * HomePage Button
     * <p>
     * Closes the form and takes you back to the home page form.
     */
    private void btnHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePageActionPerformed
        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_btnHomePageActionPerformed
     /**
     * Logout Button
     * <p>
     * Closes the form and takes you back to the login form.
     */
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        this.dispose();
        Login_Form login = new Login_Form();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        this.dispose();
        HomePage hp = new HomePage(jobRole, empID);
        hp.setVisible(true);
    }//GEN-LAST:event_Back_btnActionPerformed
    /** Filter name
     * <p>
     * Filters the list with the name entered.
     */
    private void filterName(String s){
        DefaultListModel lstModel = new DefaultListModel();
        
        for(String string : reports){
            try {
                String[] report = string.split(",");
                String dateTime = report[0];
                String name = report[1];
                
                java.util.Date strtDate = sdf.parse(report[2]);
                java.sql.Date start = new java.sql.Date(strtDate.getTime());
                
                java.util.Date endDate = sdf.parse(report[3]);
                java.sql.Date end = new java.sql.Date(endDate.getTime());
                
                String custID = report[4];
                
                if(s.equals("None")){
                    lstModel.addElement(dateTime + " - " + name + " - " + start + " - " + end + " - " + custID);
                } else if(name.equals(s)){
                    lstModel.addElement(dateTime + " - " + name + " - " + start + " - " + end + " - " + custID);
                }
            } catch (ParseException ex) {
                Logger.getLogger(View_Reports.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        reports_lst.setModel(lstModel);
    }
    /** Filter date
     * <p>
     * Filters the list with the date entered.
     */
    private void filterDate(String s){
        DefaultListModel lstModel = new DefaultListModel();
        
        for(String string : reports){
            try {
                String[] report = string.split(",");
                String dateTime = report[0];
                String name = report[1];
                
                java.util.Date strtDate = sdf.parse(report[2]);
                java.sql.Date start = new java.sql.Date(strtDate.getTime());
                
                java.util.Date endDate = sdf.parse(report[3]);
                java.sql.Date end = new java.sql.Date(endDate.getTime());
                
                String custID = report[4];
                
                if(s.equals("")){
                    lstModel.addElement(dateTime + " - " + name + " - " + start + " - " + end + " - " + custID);
                } else if(dateTime.contains(s)){
                    lstModel.addElement(dateTime + " - " + name + " - " + start + " - " + end + " - " + custID);
                }
            } catch (ParseException ex) {
                Logger.getLogger(View_Reports.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        reports_lst.setModel(lstModel);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Reports("Office Manager", "FG12").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnHomePage;
    private javax.swing.JButton btnLogOut;
    private com.toedter.calendar.JDateChooser date_dte;
    private javax.swing.JLabel filter_lbl;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton newRept_btn;
    private javax.swing.JLabel reports_lbl;
    private javax.swing.JList<String> reports_lst;
    private javax.swing.JButton reset_btn;
    private javax.swing.JComboBox<String> type_cmbo;
    private javax.swing.JButton view_btn;
    // End of variables declaration//GEN-END:variables
}
